"""
Steel Sentinel — Seed script v3 (115 węzłów, 270 krawędzi z infrastructure_db-3.json)
Uruchom z katalogu backend/: python seed.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))

from dotenv import load_dotenv
load_dotenv()

from app.database import SessionLocal, engine, Base
from app.models.infrastructure import InfrastructureNode
from app.models.graph import InfrastructureEdge
from app.models.threat import ThreatEvent

Base.metadata.create_all(bind=engine)

NODES = [
    dict(id=1, name='HSW S.A. — Zakłady Główne (Oddział I)', category='industrial',
         lat=50.582, lng=22.049, risk='critical', sector='B',
         description='Defense Industry · tier 1 · ul. Kwiatkowskiego 1, Stalowa Wola',
         resources={"Zatrudnienie": "1700 os.", "Podatność": "8.5/10"}),
    dict(id=2, name='GPZ Stalowa Wola 1 — Główny Punkt Zasilania', category='energy',
         lat=50.578, lng=22.032, risk='critical', sector='W',
         description='Power Substation · tier 1',
         resources={"Podatność": "9.0/10"}),
    dict(id=3, name='GPZ Stalowa Wola 2 — Główny Punkt Zasilania', category='energy',
         lat=50.565, lng=22.058, risk='critical', sector='D',
         description='Power Substation · tier 1',
         resources={"Podatność": "8.0/10"}),
    dict(id=4, name='Elektrociepłownia Stalowa Wola', category='energy',
         lat=50.575, lng=22.06, risk='critical', sector='B',
         description='Power Plant · tier 1',
         resources={"Podatność": "8.2/10"}),
    dict(id=5, name='Stacja Uzdatniania Wody — Stalowa Wola', category='water',
         lat=50.56, lng=22.04, risk='high', sector='D',
         description='Water Treatment · tier 1',
         resources={"Podatność": "7.5/10"}),
    dict(id=6, name='Powiatowy Szpital Specjalistyczny w Stalowej Woli', category='health',
         lat=50.5731, lng=22.0555, risk='high', sector='B',
         description='Hospital · tier 1',
         resources={"Łóżka": "380", "Podatność": "6.5/10"}),
    dict(id=7, name='Most przez rzekę San — DK77 Obwodnica', category='transport',
         lat=50.572, lng=22.015, risk='critical', sector='W',
         description='Bridge · tier 1',
         resources={"Podatność": "8.8/10"}),
    dict(id=8, name='JRG nr 1 — Jednostka Ratowniczo-Gaśnicza PSP', category='rescue',
         lat=50.574, lng=22.048, risk='medium', sector='B',
         description='Fire Station · tier 2',
         resources={"Podatność": "5.0/10"}),
    dict(id=9, name='JRG nr 2 — Jednostka Ratowniczo-Gaśnicza PSP', category='rescue',
         lat=50.558, lng=22.062, risk='medium', sector='D',
         description='Fire Station · tier 2',
         resources={}),
    dict(id=10, name='Sieć masztów BTS — łączność komórkowa', category='telecom',
         lat=50.574, lng=22.045, risk='high', sector='B',
         description='Telecom Network · tier 2',
         resources={"Podatność": "7.0/10"}),
    dict(id=11, name='Centrum Zarządzania Kryzysowego Stalowej Woli', category='administration',
         lat=50.5766, lng=22.0497, risk='high', sector='B',
         description='Emergency Management · tier 2',
         resources={"Podatność": "7.0/10"}),
    dict(id=12, name='Szpital Powiatowy im. Polskiego Czerwonego Krzyża w Nisku', category='health',
         lat=50.5197, lng=22.1466, risk='high', sector='E',
         description='Hospital · tier 1 · ul. Kościuszki 1, 37-400 Nisko',
         resources={"Łóżka": "200", "Podatność": "7.5/10"}),
    dict(id=13, name='Stacja Pogotowia Ratunkowego — Stalowa Wola', category='health',
         lat=50.5742, lng=22.0581, risk='high', sector='B',
         description='Ems Station · tier 2 · ul. Staszica 4, 37-450 Stalowa Wola',
         resources={"Podatność": "6.5/10"}),
    dict(id=14, name='Stacja Pogotowia Ratunkowego — Nisko', category='health',
         lat=50.521, lng=22.149, risk='medium', sector='E',
         description='Ems Station · tier 2 · ul. Kościuszki 1, 37-400 Nisko',
         resources={"Podatność": "6.0/10"}),
    dict(id=15, name='Przychodnia POZ Stalowa Wola — Centrum', category='health',
         lat=50.581, lng=22.049, risk='medium', sector='B',
         description='Primary Care · tier 3 · ul. Staszica 4, 37-450 Stalowa Wola',
         resources={"Podatność": "4.0/10"}),
    dict(id=16, name='Przychodnia POZ Stalowa Wola — Południe', category='health',
         lat=50.565, lng=22.038, risk='medium', sector='B',
         description='Primary Care · tier 3 · ul. Energetyków 18, 37-450 Stalowa Wola',
         resources={"Podatność": "4.0/10"}),
    dict(id=17, name='Przychodnia POZ — Rozwadów', category='health',
         lat=50.5942, lng=22.026, risk='medium', sector='B',
         description='Primary Care · tier 3 · ul. Rozwadowska, Stalowa Wola — Rozwadów',
         resources={"Podatność": "4.0/10"}),
    dict(id=18, name='Przychodnia POZ Nisko', category='health',
         lat=50.5188, lng=22.1465, risk='medium', sector='E',
         description='Primary Care · tier 3 · ul. 3 Maja, 37-400 Nisko',
         resources={"Podatność": "4.0/10"}),
    dict(id=19, name='Powiatowa Stacja Sanitarno-Epidemiologiczna', category='health',
         lat=50.5752, lng=22.051, risk='medium', sector='B',
         description='Public Health · tier 2 · ul. Staszica 4, 37-450 Stalowa Wola',
         resources={"Podatność": "5.0/10"}),
    dict(id=20, name='Apteka całodobowa — Stalowa Wola', category='food',
         lat=50.577, lng=22.053, risk='low', sector='B',
         description='Pharmacy · tier 3 · ul. Wojska Polskiego, Stalowa Wola',
         resources={"Podatność": "3.0/10"}),
    dict(id=21, name='NZOZ Dom Zdrowia (specjalistyka)', category='health',
         lat=50.579, lng=22.05, risk='low', sector='B',
         description='Specialist Clinic · tier 3 · Stalowa Wola — centrum',
         resources={"Podatność": "3.5/10"}),
    dict(id=22, name='Hospicjum w Stalowej Woli', category='health',
         lat=50.5805, lng=22.047, risk='medium', sector='B',
         description='Hospice · tier 3 · ul. Hutnicza, Stalowa Wola',
         resources={"Podatność": "4.0/10"}),
    dict(id=23, name='Dom Pomocy Społecznej — Stalowa Wola', category='health',
         lat=50.568, lng=22.042, risk='high', sector='B',
         description='Social Care · tier 2 · ul. Dmowskiego, Stalowa Wola',
         resources={"Podatność": "6.5/10"}),
    dict(id=24, name='Schron / miejsce schronienia — Popiełuszki 3', category='rescue',
         lat=50.5806, lng=22.056, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Popiełuszki 3, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=25, name='Schron / miejsce schronienia — Wyszyńskiego 14', category='rescue',
         lat=50.5821, lng=22.0532, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Wyszyńskiego 14, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=26, name='Schron / miejsce schronienia — Wyszyńskiego 17', category='rescue',
         lat=50.5824, lng=22.0538, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Wyszyńskiego 17, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=27, name='Schron / miejsce schronienia — Wyszyńskiego 19', category='rescue',
         lat=50.5826, lng=22.0542, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Wyszyńskiego 19, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=28, name='Schron / miejsce schronienia — Wyszyńskiego 19a', category='rescue',
         lat=50.5827, lng=22.0543, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Wyszyńskiego 19a, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=29, name='Schron / miejsce schronienia — Wyszyńskiego 21', category='rescue',
         lat=50.5828, lng=22.0546, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Wyszyńskiego 21, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=30, name='Schron / miejsce schronienia — Wyszyńskiego 21a', category='rescue',
         lat=50.5829, lng=22.0547, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Wyszyńskiego 21a, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=31, name='Schron / miejsce schronienia — Wyszyńskiego 23', category='rescue',
         lat=50.583, lng=22.055, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Wyszyńskiego 23, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=32, name='Schron / miejsce schronienia — Narutowicza 9', category='rescue',
         lat=50.5798, lng=22.0518, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Narutowicza 9, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=33, name='Schron / miejsce schronienia — Staszica 6', category='rescue',
         lat=50.5752, lng=22.0498, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Staszica 6, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=34, name='Schron / miejsce schronienia — Staszica 7', category='rescue',
         lat=50.5753, lng=22.05, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Staszica 7, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=35, name='Schron / miejsce schronienia — Staszica 8', category='rescue',
         lat=50.5754, lng=22.0502, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Staszica 8, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=36, name='Schron / miejsce schronienia — Staszica 9', category='rescue',
         lat=50.5755, lng=22.0504, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Staszica 9, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=37, name='Schron / miejsce schronienia — Staszica 14', category='rescue',
         lat=50.576, lng=22.051, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Staszica 14, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=38, name='Schron / miejsce schronienia — Staszica 16', category='rescue',
         lat=50.5762, lng=22.0514, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Staszica 16, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=39, name='Schron / miejsce schronienia — Staszica 18', category='rescue',
         lat=50.5764, lng=22.0518, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Staszica 18, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=40, name='Schron / miejsce schronienia — Mickiewicza 16 (PK Miasta)', category='rescue',
         lat=50.578, lng=22.049, risk='medium', sector='B',
         description='Shelter Command · tier 2 · ul. Mickiewicza 16, Stalowa Wola',
         resources={"Pojemność": "50 os.", "Podatność": "5.5/10"}),
    dict(id=41, name='Schron / miejsce schronienia — Metalowców 7', category='rescue',
         lat=50.579, lng=22.047, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Metalowców 7, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=42, name='Schron / miejsce schronienia — Metalowców 9', category='rescue',
         lat=50.5791, lng=22.0472, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Metalowców 9, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=43, name='Schron / miejsce schronienia — Hutnicza 10', category='rescue',
         lat=50.58, lng=22.0455, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Hutnicza 10, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=44, name='Schron / miejsce schronienia — Hutnicza 13', category='rescue',
         lat=50.5802, lng=22.0458, risk='medium', sector='B',
         description='Shelter Residential · tier 3 · ul. Hutnicza 13, Stalowa Wola',
         resources={"Pojemność": "150 os.", "Podatność": "4.0/10"}),
    dict(id=45, name='Kompleks schronów na terenie HSW (zbiorczo)', category='rescue',
         lat=50.582, lng=22.049, risk='high', sector='B',
         description='Shelter Industrial · tier 1 · HSW S.A., ul. Kwiatkowskiego 1, Stalowa Wola',
         resources={"Podatność": "5.0/10"}),
    dict(id=46, name='Podziemny parking z funkcją schronu (w budowie)', category='rescue',
         lat=50.58, lng=22.054, risk='medium', sector='B',
         description='Shelter Modern · tier 2 · Stalowa Wola — centrum (planowany)',
         resources={"Pojemność": "500 os.", "Podatność": "3.0/10"}),
    dict(id=47, name='Publiczna Szkoła Podstawowa nr 1 im. W. Górskiego', category='education',
         lat=50.5687, lng=22.041, risk='low', sector='B',
         description='School · tier 3 · ul. Romana Dmowskiego 9, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=48, name='Publiczna Szkoła Podstawowa nr 2 im. Jana Pawła II (Mistrzostwa Sportowego)', category='education',
         lat=50.579, lng=22.0496, risk='low', sector='B',
         description='School · tier 3 · ul. Mickiewicza, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=49, name='Publiczna Szkoła Podstawowa nr 3 im. Bohaterów Westerplatte', category='education',
         lat=50.5822, lng=22.0533, risk='low', sector='B',
         description='School · tier 3 · ul. Prymasa Stefana Wyszyńskiego 14, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=50, name='Publiczna Szkoła Podstawowa nr 4 im. E. Kwiatkowskiego', category='education',
         lat=50.566, lng=22.0395, risk='low', sector='B',
         description='School · tier 3 · ul. Niezłomnych 1, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=51, name='Publiczna Szkoła Podstawowa nr 5 im. Energetyków', category='education',
         lat=50.565, lng=22.0378, risk='low', sector='B',
         description='School · tier 3 · ul. Energetyków 18, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=52, name='Publiczna Szkoła Podstawowa nr 7 z Oddziałami Integracyjnymi', category='education',
         lat=50.5705, lng=22.042, risk='low', sector='B',
         description='School · tier 3 · ul. Generała Leopolda Okulickiego 14, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=53, name='Publiczna Szkoła Podstawowa nr 11 im. Szarych Szeregów', category='education',
         lat=50.577, lng=22.056, risk='low', sector='B',
         description='School · tier 3 · ul. Wojska Polskiego 9, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=54, name='Publiczna Szkoła Podstawowa nr 12 im. Jana Pawła II', category='education',
         lat=50.568, lng=22.045, risk='low', sector='B',
         description='School · tier 3 · ul. Józefa Poniatowskiego 55, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=55, name='I Liceum Ogólnokształcące im. KEN', category='education',
         lat=50.5755, lng=22.05, risk='low', sector='B',
         description='School · tier 3 · ul. Staszica 5, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=56, name='II Liceum Ogólnokształcące im. S. Wyspiańskiego', category='education',
         lat=50.58, lng=22.051, risk='low', sector='B',
         description='School · tier 3 · ul. 1 Sierpnia 12, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=57, name='Zespół Szkół Ponadgimnazjalnych nr 1 (technikum)', category='education',
         lat=50.576, lng=22.049, risk='low', sector='B',
         description='School · tier 3 · Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=58, name='Zespół Szkół Ponadgimnazjalnych nr 2 (technikum)', category='education',
         lat=50.577, lng=22.05, risk='low', sector='B',
         description='School · tier 3 · Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=59, name='Publiczna Szkoła Podstawowa — Nisko (centrum)', category='education',
         lat=50.5188, lng=22.1466, risk='low', sector='E',
         description='School · tier 3 · ul. 3 Maja, Nisko',
         resources={"Podatność": "3.5/10"}),
    dict(id=60, name='Publiczna Szkoła Podstawowa — Pysznica', category='education',
         lat=50.545, lng=22.085, risk='low', sector='N',
         description='School · tier 3 · ul. Wolności, Pysznica',
         resources={"Podatność": "3.5/10"}),
    dict(id=61, name='Hala MOSiR Stalowa Wola', category='rescue',
         lat=50.57, lng=22.045, risk='medium', sector='B',
         description='Evacuation Point · tier 2 · ul. Hutnicza, Stalowa Wola',
         resources={"Pojemność": "1500 os.", "Podatność": "4.5/10"}),
    dict(id=62, name='Wydział Zamiejscowy KUL w Stalowej Woli', category='education',
         lat=50.58, lng=22.044, risk='low', sector='B',
         description='University · tier 3 · ul. Ofiar Katynia 6a, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=63, name='Most na Sanie — Brandwica (droga lokalna)', category='transport',
         lat=50.563, lng=22.068, risk='critical', sector='N',
         description='Bridge · tier 1 · DW dawna trasa SW–Pysznica, Brandwica',
         resources={"Podatność": "8.0/10"}),
    dict(id=64, name='Trzeci most na Sanie (w budowie 2026)', category='transport',
         lat=50.55, lng=22.09, risk='high', sector='B',
         description='Bridge · tier 1 · DW Zaklików–SW–Pysznica–Radomyśl nad Sanem',
         resources={"Podatność": "6.5/10"}),
    dict(id=65, name='Most kolejowy nad Sanem (linia 68)', category='transport',
         lat=50.561, lng=22.067, risk='critical', sector='B',
         description='Bridge Rail · tier 1 · Linia kolejowa nr 68 Lublin–Przeworsk',
         resources={"Podatność": "8.5/10"}),
    dict(id=66, name='Most na rzece Łęg — DK77', category='transport',
         lat=50.595, lng=22.05, risk='medium', sector='B',
         description='Bridge · tier 2 · DK77 Sandomierz–Stalowa Wola–Jarosław, przeprawa Łęg',
         resources={"Podatność": "6.0/10"}),
    dict(id=67, name='Most na Sanie — Radomyśl nad Sanem', category='transport',
         lat=50.677, lng=22.044, risk='high', sector='SE',
         description='Bridge · tier 2 · Radomyśl nad Sanem, kierunek Sandomierz',
         resources={"Podatność": "6.5/10"}),
    dict(id=68, name='Dworzec PKP Stalowa Wola Rozwadów', category='transport',
         lat=50.5938, lng=22.027, risk='high', sector='B',
         description='Rail Station · tier 1 · ul. gen. Jarosława Dąbrowskiego 15, Stalowa Wola — Rozwadów',
         resources={"Podatność": "7.0/10"}),
    dict(id=69, name='Stacja PKP Stalowa Wola Centrum', category='transport',
         lat=50.578, lng=22.049, risk='medium', sector='B',
         description='Rail Station · tier 2 · Stalowa Wola — Centrum',
         resources={"Podatność": "5.5/10"}),
    dict(id=70, name='Stacja PKP Stalowa Wola Południe', category='transport',
         lat=50.555, lng=22.042, risk='medium', sector='B',
         description='Rail Station · tier 2 · Stalowa Wola — Południe',
         resources={"Podatność": "5.5/10"}),
    dict(id=71, name='Stacja PKP Nisko', category='transport',
         lat=50.516, lng=22.145, risk='medium', sector='E',
         description='Rail Station · tier 2 · Nisko',
         resources={"Podatność": "5.5/10"}),
    dict(id=72, name='Dworzec autobusowy / PKS Stalowa Wola', category='transport',
         lat=50.5775, lng=22.05, risk='medium', sector='B',
         description='Bus Station · tier 2 · ul. Dworcowa, Stalowa Wola',
         resources={"Podatność": "4.5/10"}),
    dict(id=73, name='Linia kolejowa nr 68 — odcinek powiatu', category='transport',
         lat=50.55, lng=22.07, risk='high', sector='B',
         description='Rail Line · tier 1 · Linia nr 68 — od Niska przez SW do granicy powiatu',
         resources={"Podatność": "7.5/10"}),
    dict(id=74, name='Linia Hutnicza Szerokotorowa — odcinek przy SW', category='transport',
         lat=50.61, lng=22.07, risk='critical', sector='B',
         description='Rail Line · tier 1 · LHS (1520mm) — przebiega przez powiat stalowowolski',
         resources={"Podatność": "8.0/10"}),
    dict(id=75, name='DK77 — Obwodnica Stalowej Woli', category='transport',
         lat=50.56, lng=22.07, risk='high', sector='B',
         description='Road Strategic · tier 1 · DK77 Sandomierz–Lipnik–SW–Jarosław',
         resources={"Podatność": "7.0/10"}),
    dict(id=76, name='S19 Via Carpatia — węzeł Nisko', category='transport',
         lat=50.52, lng=22.14, risk='high', sector='E',
         description='Road Strategic · tier 1 · S19 — fragment trasy Via Carpatia, węzeł Nisko',
         resources={"Podatność": "7.5/10"}),
    dict(id=77, name='Stacja paliw strategiczna — Stalowa Wola', category='chemical',
         lat=50.568, lng=22.05, risk='medium', sector='B',
         description='Fuel Station · tier 2 · Stalowa Wola — strefa przemysłowa',
         resources={"Podatność": "6.0/10"}),
    dict(id=78, name='Most na Sanie — Sokolniki (lokalny)', category='transport',
         lat=50.538, lng=22.085, risk='medium', sector='N',
         description='Bridge · tier 3 · Sokolniki, droga lokalna SW–Pysznica',
         resources={"Podatność": "4.5/10"}),
    dict(id=79, name='GPZ Nisko — Główny Punkt Zasilania', category='energy',
         lat=50.518, lng=22.15, risk='critical', sector='E',
         description='Power Substation · tier 1 · Nisko — stacja 110/15 kV',
         resources={"Podatność": "8.5/10"}),
    dict(id=80, name='Linia 110kV Stalowa Wola — Nisko', category='energy',
         lat=50.55, lng=22.1, risk='critical', sector='B',
         description='Power Line · tier 1 · Linia napowietrzna 110kV — odcinek SW-Nisko',
         resources={"Podatność": "8.0/10"}),
    dict(id=81, name='Linia 110kV Stalowa Wola — Tarnobrzeg', category='energy',
         lat=50.59, lng=22.01, risk='critical', sector='B',
         description='Power Line · tier 1 · Linia napowietrzna 110kV — kierunek Tarnobrzeg',
         resources={"Podatność": "8.0/10"}),
    dict(id=82, name='Ujęcie wody \'Krzyżowe Drogi\'', category='water',
         lat=50.565, lng=22.065, risk='critical', sector='B',
         description='Water Intake · tier 1 · Stalowa Wola, rejon Krzyżowych Dróg',
         resources={"Podatność": "8.0/10"}),
    dict(id=83, name='Ujęcie wody \'Stare Ujęcie\'', category='water',
         lat=50.575, lng=22.07, risk='critical', sector='B',
         description='Water Intake · tier 1 · Stalowa Wola — Stare Ujęcie',
         resources={"Podatność": "8.0/10"}),
    dict(id=84, name='Miejska Oczyszczalnia Ścieków (MOS)', category='water',
         lat=50.555, lng=22.07, risk='high', sector='B',
         description='Wastewater Treatment · tier 1 · ul. Działkowa 1, Stalowa Wola',
         resources={"Podatność": "7.5/10"}),
    dict(id=85, name='Stacja redukcyjno-pomiarowa gazu — Stalowa Wola', category='energy',
         lat=50.57, lng=22.06, risk='critical', sector='B',
         description='Gas Station Reduction · tier 1 · Stalowa Wola — strefa przemysłowa',
         resources={"Podatność": "8.5/10"}),
    dict(id=86, name='Sieć ciepłownicza PGE Energia Ciepła — magistrala', category='energy',
         lat=50.575, lng=22.05, risk='high', sector='B',
         description='Heating Network · tier 2 · Magistrala ciepłownicza Stalowa Wola',
         resources={"Podatność": "6.5/10"}),
    dict(id=87, name='Zbiornik retencyjny wody pitnej — Stalowa Wola', category='water',
         lat=50.58, lng=22.07, risk='medium', sector='B',
         description='Water Reservoir · tier 2 · Stalowa Wola — zbiornik wyrównawczy MZK',
         resources={"Podatność": "6.0/10"}),
    dict(id=88, name='Magazyn paliw rezerwy strategicznej (RARS)', category='chemical',
         lat=50.55, lng=22.05, risk='critical', sector='B',
         description='Fuel Depot · tier 1 · Stalowa Wola — strefa przemysłowa (założenie metodologiczne)',
         resources={"Podatność": "9.0/10"}),
    dict(id=89, name='Komenda Powiatowa Policji w Stalowej Woli', category='rescue',
         lat=50.5795, lng=22.0568, risk='high', sector='B',
         description='Police Hq · tier 1 · ul. Popiełuszki 24, 37-450 Stalowa Wola',
         resources={"Podatność": "7.0/10"}),
    dict(id=90, name='Komenda Powiatowa Policji w Nisku', category='rescue',
         lat=50.52, lng=22.1465, risk='high', sector='E',
         description='Police Hq · tier 1 · ul. Sandomierska 6, 37-400 Nisko',
         resources={"Podatność": "6.5/10"}),
    dict(id=91, name='Komisariat Policji w Pysznicy', category='rescue',
         lat=50.545, lng=22.085, risk='medium', sector='N',
         description='Police Station · tier 2 · Pysznica',
         resources={"Podatność": "5.0/10"}),
    dict(id=92, name='Komisariat Policji w Zaklikowie', category='rescue',
         lat=50.76, lng=22.13, risk='medium', sector='NW',
         description='Police Station · tier 2 · Zaklików',
         resources={"Podatność": "4.5/10"}),
    dict(id=93, name='JRG Państwowej Straży Pożarnej — Nisko', category='rescue',
         lat=50.518, lng=22.143, risk='high', sector='E',
         description='Fire Station · tier 1 · Nisko',
         resources={"Podatność": "6.0/10"}),
    dict(id=94, name='32 Batalion Lekkiej Piechoty (WOT) — Nisko', category='industrial',
         lat=50.515, lng=22.15, risk='high', sector='E',
         description='Military Unit · tier 1 · Nisko — koszary (lokalizacja zbiorcza)',
         resources={"Podatność": "7.5/10"}),
    dict(id=95, name='Wojskowe Centrum Rekrutacji — Nisko (b. WKU)', category='administration',
         lat=50.519, lng=22.147, risk='medium', sector='E',
         description='Military Recruitment · tier 2 · Nisko',
         resources={"Podatność": "5.5/10"}),
    dict(id=96, name='Urząd Miasta Stalowa Wola', category='administration',
         lat=50.581, lng=22.051, risk='high', sector='B',
         description='City Hall · tier 1 · ul. Wolności 7, 37-450 Stalowa Wola',
         resources={"Podatność": "7.0/10"}),
    dict(id=97, name='Starostwo Powiatowe w Stalowej Woli', category='administration',
         lat=50.579, lng=22.053, risk='high', sector='B',
         description='County Hall · tier 1 · ul. Podleśna 15, 37-450 Stalowa Wola',
         resources={"Podatność": "6.5/10"}),
    dict(id=98, name='Urząd Miasta i Gminy Nisko', category='administration',
         lat=50.52, lng=22.148, risk='high', sector='E',
         description='City Hall · tier 1 · Plac Wolności 14, 37-400 Nisko',
         resources={"Podatność": "6.5/10"}),
    dict(id=99, name='Urząd Gminy Pysznica', category='administration',
         lat=50.545, lng=22.086, risk='medium', sector='N',
         description='City Hall · tier 2 · ul. Wolności 322, 37-403 Pysznica',
         resources={"Podatność": "5.0/10"}),
    dict(id=100, name='Urząd Gminy Zaleszany', category='administration',
         lat=50.68, lng=21.89, risk='medium', sector='S',
         description='City Hall · tier 2 · ul. T. Kościuszki 16, 37-415 Zaleszany',
         resources={"Podatność": "4.5/10"}),
    dict(id=101, name='Urząd Gminy Bojanów', category='administration',
         lat=50.545, lng=21.98, risk='medium', sector='W',
         description='City Hall · tier 2 · Parkowa 5, 37-433 Bojanów',
         resources={"Podatność": "4.5/10"}),
    dict(id=102, name='Urząd Gminy Radomyśl nad Sanem', category='administration',
         lat=50.68, lng=22.05, risk='medium', sector='SE',
         description='City Hall · tier 2 · Rynek 32, 37-455 Radomyśl nad Sanem',
         resources={"Podatność": "4.5/10"}),
    dict(id=103, name='Urząd Gminy Zaklików', category='administration',
         lat=50.76, lng=22.13, risk='medium', sector='NW',
         description='City Hall · tier 2 · ul. Zachodnia 15, 37-470 Zaklików',
         resources={"Podatność": "4.5/10"}),
    dict(id=104, name='Sąd Rejonowy w Stalowej Woli', category='administration',
         lat=50.5775, lng=22.051, risk='medium', sector='B',
         description='Court · tier 2 · ul. Popiełuszki 7, 37-450 Stalowa Wola',
         resources={"Podatność": "5.0/10"}),
    dict(id=105, name='Prokuratura Rejonowa Stalowa Wola', category='administration',
         lat=50.578, lng=22.0515, risk='medium', sector='B',
         description='Prosecutor · tier 2 · ul. Popiełuszki, Stalowa Wola',
         resources={"Podatność": "4.5/10"}),
    dict(id=106, name='Urząd Skarbowy w Stalowej Woli', category='administration',
         lat=50.575, lng=22.049, risk='low', sector='B',
         description='Tax Office · tier 3 · ul. Hutnicza 15, Stalowa Wola',
         resources={"Podatność": "3.5/10"}),
    dict(id=107, name='LiuGong Dressta Machinery — Stalowa Wola', category='industrial',
         lat=50.578, lng=22.04, risk='medium', sector='B',
         description='Industry · tier 2 · ul. Kwiatkowskiego, Stalowa Wola — dawny teren HSW',
         resources={"Podatność": "6.0/10"}),
    dict(id=108, name='Magazyn paliw EC Stalowa Wola (węgiel/biomasa)', category='chemical',
         lat=50.586, lng=22.026, risk='high', sector='B',
         description='Fuel Storage Plant · tier 1 · ul. Energetyków 13, 37-450 Stalowa Wola',
         resources={"Podatność": "7.5/10"}),
    dict(id=109, name='Rejon Energetyczny PGE Dystrybucja — SW', category='administration',
         lat=50.58, lng=22.05, risk='medium', sector='B',
         description='Utility Office · tier 2 · Stalowa Wola — biuro RE',
         resources={"Podatność": "5.5/10"}),
    dict(id=110, name='Dyspozytornia MZK Stalowa Wola', category='administration',
         lat=50.575, lng=22.05, risk='medium', sector='B',
         description='Utility Office · tier 2 · MZK Sp. z o.o., Stalowa Wola',
         resources={"Podatność": "5.5/10"}),
    dict(id=111, name='Piekarnia przemysłowa — Stalowa Wola', category='food',
         lat=50.57, lng=22.05, risk='medium', sector='B',
         description='Food Production · tier 2 · Stalowa Wola',
         resources={"Podatność": "4.0/10"}),
    dict(id=112, name='Hipermarket strategiczny — SW (Galeria)', category='food',
         lat=50.579, lng=22.058, risk='low', sector='B',
         description='Retail Strategic · tier 3 · ul. Wolności, Stalowa Wola — Galeria',
         resources={"Podatność": "3.5/10"}),
    dict(id=113, name='Radio Leliwa — nadajnik lokalny', category='telecom',
         lat=50.578, lng=22.05, risk='medium', sector='B',
         description='Broadcast Radio · tier 2 · Stalowa Wola — studio',
         resources={"Podatność": "5.0/10"}),
    dict(id=114, name='Lokalne centrum danych / serwerownia urzędu', category='telecom',
         lat=50.581, lng=22.051, risk='medium', sector='B',
         description='Data Center · tier 2 · UM Stalowa Wola — serwerownia',
         resources={"Podatność": "6.0/10"}),
    dict(id=115, name='Cmentarz komunalny — Stalowa Wola', category='administration',
         lat=50.565, lng=22.07, risk='low', sector='B',
         description='Cemetery · tier 3 · ul. Cmentarna, Stalowa Wola',
         resources={"Podatność": "2.0/10"}),
]

EDGES = [
    dict(source_id=2, target_id=1, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=1, dependency_type='water', weight=1.0, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=85, target_id=1, dependency_type='fuel', weight=1.0, hours_to_impact=0.17, description='HSW potrzebuje gazu do procesów technologicznych (piece, obróbka cieplna).'),
    dict(source_id=75, target_id=1, dependency_type='transport', weight=1.0, hours_to_impact=0.0, description='Dostawy materiałów i odbiór produktów.'),
    dict(source_id=68, target_id=1, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Kolejowy transport ciężki.'),
    dict(source_id=4, target_id=2, dependency_type='energy', weight=0.5, hours_to_impact=0.03, description='EC jest lokalnym źródłem mocy. Przy braku EC sieć 110kV przejmuje obciążenie.'),
    dict(source_id=81, target_id=2, dependency_type='energy', weight=0.5, hours_to_impact=0.02, description='Linia 110kV od strony Tarnobrzega — jedno z zasilań.'),
    dict(source_id=4, target_id=3, dependency_type='energy', weight=0.5, hours_to_impact=0.03, description='EC jest lokalnym źródłem mocy. Przy braku EC sieć 110kV przejmuje obciążenie.'),
    dict(source_id=2, target_id=4, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=85, target_id=4, dependency_type='fuel', weight=1.0, hours_to_impact=0.0, description='EC Stalowa Wola jest gazowo-parowa (PGE EC) — bez gazu nie działa.'),
    dict(source_id=108, target_id=4, dependency_type='fuel', weight=0.5, hours_to_impact=0.5, description='Magazyn paliw EC — bufor lokalny.'),
    dict(source_id=5, target_id=4, dependency_type='water', weight=0.5, hours_to_impact=1.0, description='Woda technologiczna do chłodzenia.'),
    dict(source_id=2, target_id=5, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=82, target_id=5, dependency_type='water', weight=1.0, hours_to_impact=1.0, description='Jedno z dwóch ujęć MZK. Drugie jako backup.'),
    dict(source_id=83, target_id=5, dependency_type='water', weight=1.0, hours_to_impact=1.0, description='Drugie ujęcie MZK.'),
    dict(source_id=2, target_id=6, dependency_type='energy', weight=1.0, hours_to_impact=24.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 1440 min, potem stop.'),
    dict(source_id=5, target_id=6, dependency_type='water', weight=1.0, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=6, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=6, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=12, target_id=6, dependency_type='energy', weight=0.5, hours_to_impact=0.0, description='Szpital Nisko jako redundancja (~45 min jazdy).'),
    dict(source_id=2, target_id=8, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=10, target_id=8, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=77, target_id=8, dependency_type='fuel', weight=0.5, hours_to_impact=24.0, description='Tankowanie pojazdów. Bufor lokalny ~24h.'),
    dict(source_id=11, target_id=8, dependency_type='telecom', weight=0.5, hours_to_impact=0.17, description='CZK koordynuje akcje ratownicze powiatu.'),
    dict(source_id=2, target_id=9, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=10, target_id=9, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=77, target_id=9, dependency_type='fuel', weight=0.5, hours_to_impact=24.0, description='Tankowanie pojazdów. Bufor lokalny ~24h.'),
    dict(source_id=11, target_id=9, dependency_type='telecom', weight=0.5, hours_to_impact=0.17, description='CZK koordynuje akcje ratownicze powiatu.'),
    dict(source_id=2, target_id=10, dependency_type='energy', weight=1.0, hours_to_impact=3.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 180 min, potem stop.'),
    dict(source_id=2, target_id=11, dependency_type='energy', weight=1.0, hours_to_impact=12.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 720 min, potem stop.'),
    dict(source_id=5, target_id=11, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=11, dependency_type='telecom', weight=0.5, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=79, target_id=12, dependency_type='energy', weight=1.0, hours_to_impact=24.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 1440 min, potem stop.'),
    dict(source_id=5, target_id=12, dependency_type='water', weight=1.0, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=12, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=12, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=6, target_id=12, dependency_type='energy', weight=0.5, hours_to_impact=0.0, description='Szpital PCK jako redundancja.'),
    dict(source_id=2, target_id=13, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=13, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=13, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=77, target_id=13, dependency_type='fuel', weight=0.5, hours_to_impact=24.0, description='Tankowanie pojazdów. Bufor lokalny ~24h.'),
    dict(source_id=11, target_id=13, dependency_type='telecom', weight=0.5, hours_to_impact=0.17, description='CZK koordynuje akcje ratownicze powiatu.'),
    dict(source_id=79, target_id=14, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=14, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=14, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=77, target_id=14, dependency_type='fuel', weight=0.5, hours_to_impact=24.0, description='Tankowanie pojazdów. Bufor lokalny ~24h.'),
    dict(source_id=11, target_id=14, dependency_type='telecom', weight=0.5, hours_to_impact=0.17, description='CZK koordynuje akcje ratownicze powiatu.'),
    dict(source_id=2, target_id=15, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=15, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=16, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=16, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=17, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=17, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=79, target_id=18, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=18, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=19, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=10, target_id=19, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=2, target_id=20, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=2, target_id=21, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=21, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=22, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=22, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=22, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=23, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=23, dependency_type='water', weight=1.0, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=23, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=24, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=24, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=25, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=25, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=26, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=26, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=27, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=27, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=28, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=28, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=29, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=29, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=30, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=30, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=31, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=31, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=32, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=32, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=33, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=33, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=34, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=34, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=35, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=35, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=36, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=36, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=37, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=37, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=38, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=38, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=39, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=39, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=40, dependency_type='energy', weight=1.0, hours_to_impact=12.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 720 min, potem stop.'),
    dict(source_id=5, target_id=40, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=41, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=41, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=42, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=42, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=43, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=43, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=44, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=44, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=45, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=5, target_id=45, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=1, target_id=45, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Schrony zakładowe — zasilane z sieci wewnętrznej HSW.'),
    dict(source_id=2, target_id=46, dependency_type='energy', weight=1.0, hours_to_impact=6.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 360 min, potem stop.'),
    dict(source_id=5, target_id=46, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=3, target_id=46, dependency_type='energy', weight=1.0, hours_to_impact=6.0, description='Nowoczesny schron — własny UPS/generator.'),
    dict(source_id=2, target_id=47, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=47, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=47, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=48, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=48, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=48, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=49, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=49, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=49, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=50, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=50, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=50, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=51, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=51, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=51, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=52, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=52, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=52, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=53, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=53, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=53, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=54, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=54, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=54, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=55, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=55, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=55, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=56, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=56, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=56, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=57, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=57, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=57, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=58, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=58, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=58, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=79, target_id=59, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=59, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=59, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=60, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=60, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=60, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=7, target_id=60, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.'),
    dict(source_id=2, target_id=61, dependency_type='energy', weight=1.0, hours_to_impact=1.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 60 min, potem stop.'),
    dict(source_id=5, target_id=61, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=62, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=62, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=86, target_id=62, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=7, target_id=64, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.'),
    dict(source_id=2, target_id=68, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=73, target_id=68, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Stacja bez linii kolejowej traci funkcję.'),
    dict(source_id=2, target_id=69, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=73, target_id=69, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Stacja bez linii kolejowej traci funkcję.'),
    dict(source_id=2, target_id=70, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=73, target_id=70, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Stacja bez linii kolejowej traci funkcję.'),
    dict(source_id=79, target_id=71, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=73, target_id=71, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Stacja bez linii kolejowej traci funkcję.'),
    dict(source_id=2, target_id=72, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=65, target_id=73, dependency_type='transport', weight=1.0, hours_to_impact=0.0, description='Przeprawa przez San — bez mostu linia 68 przerwana.'),
    dict(source_id=2, target_id=77, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=7, target_id=78, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.'),
    dict(source_id=4, target_id=79, dependency_type='energy', weight=0.5, hours_to_impact=0.03, description='EC jest lokalnym źródłem mocy. Przy braku EC sieć 110kV przejmuje obciążenie.'),
    dict(source_id=80, target_id=79, dependency_type='energy', weight=1.0, hours_to_impact=0.02, description='Główne zasilanie GPZ Nisko z linii SW–Nisko.'),
    dict(source_id=7, target_id=80, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.'),
    dict(source_id=2, target_id=82, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=2, target_id=83, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=2, target_id=84, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=84, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=85, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=2, target_id=86, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=4, target_id=86, dependency_type='energy', weight=1.0, hours_to_impact=0.17, description='Magistrala bierze ciepło z EC.'),
    dict(source_id=2, target_id=87, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=2, target_id=88, dependency_type='energy', weight=1.0, hours_to_impact=1.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 60 min, potem stop.'),
    dict(source_id=2, target_id=89, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=10, target_id=89, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=79, target_id=90, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=10, target_id=90, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=2, target_id=91, dependency_type='energy', weight=1.0, hours_to_impact=1.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 60 min, potem stop.'),
    dict(source_id=10, target_id=91, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=7, target_id=91, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.'),
    dict(source_id=89, target_id=91, dependency_type='telecom', weight=0.5, hours_to_impact=0.17, description='Komenda powiatowa koordynuje dyżury.'),
    dict(source_id=2, target_id=92, dependency_type='energy', weight=1.0, hours_to_impact=1.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 60 min, potem stop.'),
    dict(source_id=10, target_id=92, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=67, target_id=92, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.'),
    dict(source_id=89, target_id=92, dependency_type='telecom', weight=0.5, hours_to_impact=0.17, description='Komenda powiatowa koordynuje dyżury.'),
    dict(source_id=79, target_id=93, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=10, target_id=93, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=77, target_id=93, dependency_type='fuel', weight=0.5, hours_to_impact=24.0, description='Tankowanie pojazdów. Bufor lokalny ~24h.'),
    dict(source_id=11, target_id=93, dependency_type='telecom', weight=0.5, hours_to_impact=0.17, description='CZK koordynuje akcje ratownicze powiatu.'),
    dict(source_id=79, target_id=94, dependency_type='energy', weight=1.0, hours_to_impact=8.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 480 min, potem stop.'),
    dict(source_id=10, target_id=94, dependency_type='telecom', weight=0.5, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=77, target_id=94, dependency_type='fuel', weight=0.5, hours_to_impact=24.0, description='Tankowanie pojazdów. Bufor lokalny ~24h.'),
    dict(source_id=79, target_id=95, dependency_type='energy', weight=1.0, hours_to_impact=1.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 60 min, potem stop.'),
    dict(source_id=2, target_id=96, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=96, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=96, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=96, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=97, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=97, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=97, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=97, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=79, target_id=98, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_nisko. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=98, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=98, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=98, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=99, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=99, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=99, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=99, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=7, target_id=99, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.'),
    dict(source_id=2, target_id=100, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=100, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=100, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=100, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=101, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=101, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=101, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=101, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=102, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=102, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=102, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=102, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=2, target_id=103, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=103, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=103, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=86, target_id=103, dependency_type='energy', weight=0.5, hours_to_impact=4.0, description='Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.'),
    dict(source_id=67, target_id=103, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.'),
    dict(source_id=2, target_id=104, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=104, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=104, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=2, target_id=105, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=105, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=10, target_id=105, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=2, target_id=106, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=2, target_id=107, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=107, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=85, target_id=107, dependency_type='fuel', weight=0.5, hours_to_impact=0.25, description=''),
    dict(source_id=2, target_id=108, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=68, target_id=108, dependency_type='transport', weight=0.5, hours_to_impact=0.0, description='Dostawy węgla/biomasy koleją.'),
    dict(source_id=2, target_id=109, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=10, target_id=109, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=2, target_id=110, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=10, target_id=110, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=2, target_id=111, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=111, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=85, target_id=111, dependency_type='fuel', weight=1.0, hours_to_impact=0.17, description='Piekarnia — gaz do pieców.'),
    dict(source_id=2, target_id=112, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=112, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
    dict(source_id=2, target_id=113, dependency_type='energy', weight=1.0, hours_to_impact=4.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.'),
    dict(source_id=10, target_id=113, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=2, target_id=114, dependency_type='energy', weight=1.0, hours_to_impact=2.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 120 min, potem stop.'),
    dict(source_id=10, target_id=114, dependency_type='telecom', weight=1.0, hours_to_impact=1.0, description='Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.'),
    dict(source_id=2, target_id=115, dependency_type='energy', weight=1.0, hours_to_impact=0.0, description='Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.'),
    dict(source_id=5, target_id=115, dependency_type='water', weight=0.5, hours_to_impact=2.0, description='Woda pitna z SUW. Mały bufor (zbiorniki lokalne).'),
]


def seed():
    db = SessionLocal()
    try:
        db.query(ThreatEvent).delete()
        db.query(InfrastructureEdge).delete()
        db.query(InfrastructureNode).delete()
        db.commit()

        for n in NODES:
            resources = n.pop("resources", {})
            node = InfrastructureNode(
                **n, resources=resources, is_active=True,
            )
            db.add(node)
        db.commit()
        print(f"✅ Wstawiono {len(NODES)} węzłów infrastruktury")

        for e in EDGES:
            db.add(InfrastructureEdge(**e))
        db.commit()
        print(f"✅ Wstawiono {len(EDGES)} krawędzi grafu zależności")

        print("\n🛡️  Baza danych Steel Sentinel v3 gotowa! (115 obiektów, 270 krawędzi)")

    except Exception as ex:
        db.rollback()
        print(f"❌ Błąd: {ex}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()