// ============================================================
// STEEL SENTINEL — Local data (fallback when API unavailable)
// Generated from infrastructure_db-2.json (115 obiektów, v3.0)
// ============================================================

export const STALOWA_WOLA_CENTER = [50.5833, 22.0500]

export const CATEGORIES = {
  energy:         { label: 'Energetyczna',     icon: '⚡', color: '#ffeb3b' },
  water:          { label: 'Wodociągowa',       icon: '💧', color: '#4fc3f7' },
  health:         { label: 'Ochrona zdrowia',   icon: '🏥', color: '#f48fb1' },
  transport:      { label: 'Transportowa',      icon: '🌉', color: '#a5d6a7' },
  telecom:        { label: 'Łączność',          icon: '📡', color: '#ce93d8' },
  industrial:     { label: 'Przemysłowa',       icon: '🏭', color: '#ef9a9a' },
  administration: { label: 'Administracja',     icon: '🏛️', color: '#90caf9' },
  rescue:         { label: 'Ratownicza',        icon: '🚒', color: '#ffcc80' },
  chemical:       { label: 'Chemiczna/Paliwa',  icon: '🛢️', color: '#ff8a65' },
  food:           { label: 'Zaopatrzenie',      icon: '🏪', color: '#c5e1a5' },
  education:      { label: 'Edukacja/Schrony',  icon: '🏫', color: '#ffe082' },
}

export const INFRASTRUCTURE = [
  { id: 1, name: `HSW S.A. — Zakłady Główne (Oddział I)`, category: 'industrial',
    lat: 50.582, lng: 22.049, risk: 'critical', sector: 'B',
    description: `Defense Industry · tier 1 · ul. Kwiatkowskiego 1, Stalowa Wola`,
    resources: {"Zatrudnienie": "1700 os.", "Podatność": "8.5/10"} },
  { id: 2, name: `GPZ Stalowa Wola 1 — Główny Punkt Zasilania`, category: 'energy',
    lat: 50.578, lng: 22.032, risk: 'critical', sector: 'W',
    description: `Power Substation · tier 1`,
    resources: {"Podatność": "9.0/10"} },
  { id: 3, name: `GPZ Stalowa Wola 2 — Główny Punkt Zasilania`, category: 'energy',
    lat: 50.565, lng: 22.058, risk: 'critical', sector: 'D',
    description: `Power Substation · tier 1`,
    resources: {"Podatność": "8.0/10"} },
  { id: 4, name: `Elektrociepłownia Stalowa Wola`, category: 'energy',
    lat: 50.575, lng: 22.06, risk: 'critical', sector: 'B',
    description: `Power Plant · tier 1`,
    resources: {"Podatność": "8.2/10"} },
  { id: 5, name: `Stacja Uzdatniania Wody — Stalowa Wola`, category: 'water',
    lat: 50.56, lng: 22.04, risk: 'high', sector: 'D',
    description: `Water Treatment · tier 1`,
    resources: {"Podatność": "7.5/10"} },
  { id: 6, name: `Powiatowy Szpital Specjalistyczny w Stalowej Woli`, category: 'health',
    lat: 50.5731, lng: 22.0555, risk: 'high', sector: 'B',
    description: `Hospital · tier 1`,
    resources: {"Łóżka": "380", "Podatność": "6.5/10"} },
  { id: 7, name: `Most przez rzekę San — DK77 Obwodnica`, category: 'transport',
    lat: 50.572, lng: 22.015, risk: 'critical', sector: 'W',
    description: `Bridge · tier 1`,
    resources: {"Podatność": "8.8/10"} },
  { id: 8, name: `JRG nr 1 — Jednostka Ratowniczo-Gaśnicza PSP`, category: 'rescue',
    lat: 50.574, lng: 22.048, risk: 'medium', sector: 'B',
    description: `Fire Station · tier 2`,
    resources: {"Podatność": "5.0/10"} },
  { id: 9, name: `JRG nr 2 — Jednostka Ratowniczo-Gaśnicza PSP`, category: 'rescue',
    lat: 50.558, lng: 22.062, risk: 'medium', sector: 'D',
    description: `Fire Station · tier 2`,
    resources: {} },
  { id: 10, name: `Sieć masztów BTS — łączność komórkowa`, category: 'telecom',
    lat: 50.574, lng: 22.045, risk: 'high', sector: 'B',
    description: `Telecom Network · tier 2`,
    resources: {"Podatność": "7.0/10"} },
  { id: 11, name: `Centrum Zarządzania Kryzysowego Stalowej Woli`, category: 'administration',
    lat: 50.5766, lng: 22.0497, risk: 'high', sector: 'B',
    description: `Emergency Management · tier 2`,
    resources: {"Podatność": "7.0/10"} },
  { id: 12, name: `Szpital Powiatowy im. Polskiego Czerwonego Krzyża w Nisku`, category: 'health',
    lat: 50.5197, lng: 22.1466, risk: 'high', sector: 'E',
    description: `Hospital · tier 1 · ul. Kościuszki 1, 37-400 Nisko`,
    resources: {"Łóżka": "200", "Podatność": "7.5/10"} },
  { id: 13, name: `Stacja Pogotowia Ratunkowego — Stalowa Wola`, category: 'health',
    lat: 50.5742, lng: 22.0581, risk: 'high', sector: 'B',
    description: `Ems Station · tier 2 · ul. Staszica 4, 37-450 Stalowa Wola`,
    resources: {"Podatność": "6.5/10"} },
  { id: 14, name: `Stacja Pogotowia Ratunkowego — Nisko`, category: 'health',
    lat: 50.521, lng: 22.149, risk: 'medium', sector: 'E',
    description: `Ems Station · tier 2 · ul. Kościuszki 1, 37-400 Nisko`,
    resources: {"Podatność": "6.0/10"} },
  { id: 15, name: `Przychodnia POZ Stalowa Wola — Centrum`, category: 'health',
    lat: 50.581, lng: 22.049, risk: 'medium', sector: 'B',
    description: `Primary Care · tier 3 · ul. Staszica 4, 37-450 Stalowa Wola`,
    resources: {"Podatność": "4.0/10"} },
  { id: 16, name: `Przychodnia POZ Stalowa Wola — Południe`, category: 'health',
    lat: 50.565, lng: 22.038, risk: 'medium', sector: 'B',
    description: `Primary Care · tier 3 · ul. Energetyków 18, 37-450 Stalowa Wola`,
    resources: {"Podatność": "4.0/10"} },
  { id: 17, name: `Przychodnia POZ — Rozwadów`, category: 'health',
    lat: 50.5942, lng: 22.026, risk: 'medium', sector: 'B',
    description: `Primary Care · tier 3 · ul. Rozwadowska, Stalowa Wola — Rozwadów`,
    resources: {"Podatność": "4.0/10"} },
  { id: 18, name: `Przychodnia POZ Nisko`, category: 'health',
    lat: 50.5188, lng: 22.1465, risk: 'medium', sector: 'E',
    description: `Primary Care · tier 3 · ul. 3 Maja, 37-400 Nisko`,
    resources: {"Podatność": "4.0/10"} },
  { id: 19, name: `Powiatowa Stacja Sanitarno-Epidemiologiczna`, category: 'health',
    lat: 50.5752, lng: 22.051, risk: 'medium', sector: 'B',
    description: `Public Health · tier 2 · ul. Staszica 4, 37-450 Stalowa Wola`,
    resources: {"Podatność": "5.0/10"} },
  { id: 20, name: `Apteka całodobowa — Stalowa Wola`, category: 'food',
    lat: 50.577, lng: 22.053, risk: 'low', sector: 'B',
    description: `Pharmacy · tier 3 · ul. Wojska Polskiego, Stalowa Wola`,
    resources: {"Podatność": "3.0/10"} },
  { id: 21, name: `NZOZ Dom Zdrowia (specjalistyka)`, category: 'health',
    lat: 50.579, lng: 22.05, risk: 'low', sector: 'B',
    description: `Specialist Clinic · tier 3 · Stalowa Wola — centrum`,
    resources: {"Podatność": "3.5/10"} },
  { id: 22, name: `Hospicjum w Stalowej Woli`, category: 'health',
    lat: 50.5805, lng: 22.047, risk: 'medium', sector: 'B',
    description: `Hospice · tier 3 · ul. Hutnicza, Stalowa Wola`,
    resources: {"Podatność": "4.0/10"} },
  { id: 23, name: `Dom Pomocy Społecznej — Stalowa Wola`, category: 'health',
    lat: 50.568, lng: 22.042, risk: 'high', sector: 'B',
    description: `Social Care · tier 2 · ul. Dmowskiego, Stalowa Wola`,
    resources: {"Podatność": "6.5/10"} },
  { id: 24, name: `Schron / miejsce schronienia — Popiełuszki 3`, category: 'rescue',
    lat: 50.5806, lng: 22.056, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Popiełuszki 3, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 25, name: `Schron / miejsce schronienia — Wyszyńskiego 14`, category: 'rescue',
    lat: 50.5821, lng: 22.0532, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Wyszyńskiego 14, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 26, name: `Schron / miejsce schronienia — Wyszyńskiego 17`, category: 'rescue',
    lat: 50.5824, lng: 22.0538, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Wyszyńskiego 17, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 27, name: `Schron / miejsce schronienia — Wyszyńskiego 19`, category: 'rescue',
    lat: 50.5826, lng: 22.0542, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Wyszyńskiego 19, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 28, name: `Schron / miejsce schronienia — Wyszyńskiego 19a`, category: 'rescue',
    lat: 50.5827, lng: 22.0543, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Wyszyńskiego 19a, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 29, name: `Schron / miejsce schronienia — Wyszyńskiego 21`, category: 'rescue',
    lat: 50.5828, lng: 22.0546, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Wyszyńskiego 21, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 30, name: `Schron / miejsce schronienia — Wyszyńskiego 21a`, category: 'rescue',
    lat: 50.5829, lng: 22.0547, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Wyszyńskiego 21a, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 31, name: `Schron / miejsce schronienia — Wyszyńskiego 23`, category: 'rescue',
    lat: 50.583, lng: 22.055, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Wyszyńskiego 23, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 32, name: `Schron / miejsce schronienia — Narutowicza 9`, category: 'rescue',
    lat: 50.5798, lng: 22.0518, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Narutowicza 9, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 33, name: `Schron / miejsce schronienia — Staszica 6`, category: 'rescue',
    lat: 50.5752, lng: 22.0498, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Staszica 6, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 34, name: `Schron / miejsce schronienia — Staszica 7`, category: 'rescue',
    lat: 50.5753, lng: 22.05, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Staszica 7, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 35, name: `Schron / miejsce schronienia — Staszica 8`, category: 'rescue',
    lat: 50.5754, lng: 22.0502, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Staszica 8, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 36, name: `Schron / miejsce schronienia — Staszica 9`, category: 'rescue',
    lat: 50.5755, lng: 22.0504, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Staszica 9, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 37, name: `Schron / miejsce schronienia — Staszica 14`, category: 'rescue',
    lat: 50.576, lng: 22.051, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Staszica 14, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 38, name: `Schron / miejsce schronienia — Staszica 16`, category: 'rescue',
    lat: 50.5762, lng: 22.0514, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Staszica 16, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 39, name: `Schron / miejsce schronienia — Staszica 18`, category: 'rescue',
    lat: 50.5764, lng: 22.0518, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Staszica 18, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 40, name: `Schron / miejsce schronienia — Mickiewicza 16 (PK Miasta)`, category: 'rescue',
    lat: 50.578, lng: 22.049, risk: 'medium', sector: 'B',
    description: `Shelter Command · tier 2 · ul. Mickiewicza 16, Stalowa Wola`,
    resources: {"Pojemność": "50 os.", "Podatność": "5.5/10"} },
  { id: 41, name: `Schron / miejsce schronienia — Metalowców 7`, category: 'rescue',
    lat: 50.579, lng: 22.047, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Metalowców 7, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 42, name: `Schron / miejsce schronienia — Metalowców 9`, category: 'rescue',
    lat: 50.5791, lng: 22.0472, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Metalowców 9, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 43, name: `Schron / miejsce schronienia — Hutnicza 10`, category: 'rescue',
    lat: 50.58, lng: 22.0455, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Hutnicza 10, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 44, name: `Schron / miejsce schronienia — Hutnicza 13`, category: 'rescue',
    lat: 50.5802, lng: 22.0458, risk: 'medium', sector: 'B',
    description: `Shelter Residential · tier 3 · ul. Hutnicza 13, Stalowa Wola`,
    resources: {"Pojemność": "150 os.", "Podatność": "4.0/10"} },
  { id: 45, name: `Kompleks schronów na terenie HSW (zbiorczo)`, category: 'rescue',
    lat: 50.582, lng: 22.049, risk: 'high', sector: 'B',
    description: `Shelter Industrial · tier 1 · HSW S.A., ul. Kwiatkowskiego 1, Stalowa Wola`,
    resources: {"Podatność": "5.0/10"} },
  { id: 46, name: `Podziemny parking z funkcją schronu (w budowie)`, category: 'rescue',
    lat: 50.58, lng: 22.054, risk: 'medium', sector: 'B',
    description: `Shelter Modern · tier 2 · Stalowa Wola — centrum (planowany)`,
    resources: {"Pojemność": "500 os.", "Podatność": "3.0/10"} },
  { id: 47, name: `Publiczna Szkoła Podstawowa nr 1 im. W. Górskiego`, category: 'education',
    lat: 50.5687, lng: 22.041, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Romana Dmowskiego 9, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 48, name: `Publiczna Szkoła Podstawowa nr 2 im. Jana Pawła II (Mistrzostwa Sportowego)`, category: 'education',
    lat: 50.579, lng: 22.0496, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Mickiewicza, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 49, name: `Publiczna Szkoła Podstawowa nr 3 im. Bohaterów Westerplatte`, category: 'education',
    lat: 50.5822, lng: 22.0533, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Prymasa Stefana Wyszyńskiego 14, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 50, name: `Publiczna Szkoła Podstawowa nr 4 im. E. Kwiatkowskiego`, category: 'education',
    lat: 50.566, lng: 22.0395, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Niezłomnych 1, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 51, name: `Publiczna Szkoła Podstawowa nr 5 im. Energetyków`, category: 'education',
    lat: 50.565, lng: 22.0378, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Energetyków 18, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 52, name: `Publiczna Szkoła Podstawowa nr 7 z Oddziałami Integracyjnymi`, category: 'education',
    lat: 50.5705, lng: 22.042, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Generała Leopolda Okulickiego 14, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 53, name: `Publiczna Szkoła Podstawowa nr 11 im. Szarych Szeregów`, category: 'education',
    lat: 50.577, lng: 22.056, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Wojska Polskiego 9, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 54, name: `Publiczna Szkoła Podstawowa nr 12 im. Jana Pawła II`, category: 'education',
    lat: 50.568, lng: 22.045, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Józefa Poniatowskiego 55, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 55, name: `I Liceum Ogólnokształcące im. KEN`, category: 'education',
    lat: 50.5755, lng: 22.05, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. Staszica 5, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 56, name: `II Liceum Ogólnokształcące im. S. Wyspiańskiego`, category: 'education',
    lat: 50.58, lng: 22.051, risk: 'low', sector: 'B',
    description: `School · tier 3 · ul. 1 Sierpnia 12, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 57, name: `Zespół Szkół Ponadgimnazjalnych nr 1 (technikum)`, category: 'education',
    lat: 50.576, lng: 22.049, risk: 'low', sector: 'B',
    description: `School · tier 3 · Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 58, name: `Zespół Szkół Ponadgimnazjalnych nr 2 (technikum)`, category: 'education',
    lat: 50.577, lng: 22.05, risk: 'low', sector: 'B',
    description: `School · tier 3 · Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 59, name: `Publiczna Szkoła Podstawowa — Nisko (centrum)`, category: 'education',
    lat: 50.5188, lng: 22.1466, risk: 'low', sector: 'E',
    description: `School · tier 3 · ul. 3 Maja, Nisko`,
    resources: {"Podatność": "3.5/10"} },
  { id: 60, name: `Publiczna Szkoła Podstawowa — Pysznica`, category: 'education',
    lat: 50.545, lng: 22.085, risk: 'low', sector: 'N',
    description: `School · tier 3 · ul. Wolności, Pysznica`,
    resources: {"Podatność": "3.5/10"} },
  { id: 61, name: `Hala MOSiR Stalowa Wola`, category: 'rescue',
    lat: 50.57, lng: 22.045, risk: 'medium', sector: 'B',
    description: `Evacuation Point · tier 2 · ul. Hutnicza, Stalowa Wola`,
    resources: {"Pojemność": "1500 os.", "Podatność": "4.5/10"} },
  { id: 62, name: `Wydział Zamiejscowy KUL w Stalowej Woli`, category: 'education',
    lat: 50.58, lng: 22.044, risk: 'low', sector: 'B',
    description: `University · tier 3 · ul. Ofiar Katynia 6a, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 63, name: `Most na Sanie — Brandwica (droga lokalna)`, category: 'transport',
    lat: 50.563, lng: 22.068, risk: 'critical', sector: 'N',
    description: `Bridge · tier 1 · DW dawna trasa SW–Pysznica, Brandwica`,
    resources: {"Podatność": "8.0/10"} },
  { id: 64, name: `Trzeci most na Sanie (w budowie 2026)`, category: 'transport',
    lat: 50.55, lng: 22.09, risk: 'high', sector: 'B',
    description: `Bridge · tier 1 · DW Zaklików–SW–Pysznica–Radomyśl nad Sanem`,
    resources: {"Podatność": "6.5/10"} },
  { id: 65, name: `Most kolejowy nad Sanem (linia 68)`, category: 'transport',
    lat: 50.561, lng: 22.067, risk: 'critical', sector: 'B',
    description: `Bridge Rail · tier 1 · Linia kolejowa nr 68 Lublin–Przeworsk`,
    resources: {"Podatność": "8.5/10"} },
  { id: 66, name: `Most na rzece Łęg — DK77`, category: 'transport',
    lat: 50.595, lng: 22.05, risk: 'medium', sector: 'B',
    description: `Bridge · tier 2 · DK77 Sandomierz–Stalowa Wola–Jarosław, przeprawa Łęg`,
    resources: {"Podatność": "6.0/10"} },
  { id: 67, name: `Most na Sanie — Radomyśl nad Sanem`, category: 'transport',
    lat: 50.677, lng: 22.044, risk: 'high', sector: 'SE',
    description: `Bridge · tier 2 · Radomyśl nad Sanem, kierunek Sandomierz`,
    resources: {"Podatność": "6.5/10"} },
  { id: 68, name: `Dworzec PKP Stalowa Wola Rozwadów`, category: 'transport',
    lat: 50.5938, lng: 22.027, risk: 'high', sector: 'B',
    description: `Rail Station · tier 1 · ul. gen. Jarosława Dąbrowskiego 15, Stalowa Wola — Rozwadów`,
    resources: {"Podatność": "7.0/10"} },
  { id: 69, name: `Stacja PKP Stalowa Wola Centrum`, category: 'transport',
    lat: 50.578, lng: 22.049, risk: 'medium', sector: 'B',
    description: `Rail Station · tier 2 · Stalowa Wola — Centrum`,
    resources: {"Podatność": "5.5/10"} },
  { id: 70, name: `Stacja PKP Stalowa Wola Południe`, category: 'transport',
    lat: 50.555, lng: 22.042, risk: 'medium', sector: 'B',
    description: `Rail Station · tier 2 · Stalowa Wola — Południe`,
    resources: {"Podatność": "5.5/10"} },
  { id: 71, name: `Stacja PKP Nisko`, category: 'transport',
    lat: 50.516, lng: 22.145, risk: 'medium', sector: 'E',
    description: `Rail Station · tier 2 · Nisko`,
    resources: {"Podatność": "5.5/10"} },
  { id: 72, name: `Dworzec autobusowy / PKS Stalowa Wola`, category: 'transport',
    lat: 50.5775, lng: 22.05, risk: 'medium', sector: 'B',
    description: `Bus Station · tier 2 · ul. Dworcowa, Stalowa Wola`,
    resources: {"Podatność": "4.5/10"} },
  { id: 73, name: `Linia kolejowa nr 68 — odcinek powiatu`, category: 'transport',
    lat: 50.55, lng: 22.07, risk: 'high', sector: 'B',
    description: `Rail Line · tier 1 · Linia nr 68 — od Niska przez SW do granicy powiatu`,
    resources: {"Podatność": "7.5/10"} },
  { id: 74, name: `Linia Hutnicza Szerokotorowa — odcinek przy SW`, category: 'transport',
    lat: 50.61, lng: 22.07, risk: 'critical', sector: 'B',
    description: `Rail Line · tier 1 · LHS (1520mm) — przebiega przez powiat stalowowolski`,
    resources: {"Podatność": "8.0/10"} },
  { id: 75, name: `DK77 — Obwodnica Stalowej Woli`, category: 'transport',
    lat: 50.56, lng: 22.07, risk: 'high', sector: 'B',
    description: `Road Strategic · tier 1 · DK77 Sandomierz–Lipnik–SW–Jarosław`,
    resources: {"Podatność": "7.0/10"} },
  { id: 76, name: `S19 Via Carpatia — węzeł Nisko`, category: 'transport',
    lat: 50.52, lng: 22.14, risk: 'high', sector: 'E',
    description: `Road Strategic · tier 1 · S19 — fragment trasy Via Carpatia, węzeł Nisko`,
    resources: {"Podatność": "7.5/10"} },
  { id: 77, name: `Stacja paliw strategiczna — Stalowa Wola`, category: 'chemical',
    lat: 50.568, lng: 22.05, risk: 'medium', sector: 'B',
    description: `Fuel Station · tier 2 · Stalowa Wola — strefa przemysłowa`,
    resources: {"Podatność": "6.0/10"} },
  { id: 78, name: `Most na Sanie — Sokolniki (lokalny)`, category: 'transport',
    lat: 50.538, lng: 22.085, risk: 'medium', sector: 'N',
    description: `Bridge · tier 3 · Sokolniki, droga lokalna SW–Pysznica`,
    resources: {"Podatność": "4.5/10"} },
  { id: 79, name: `GPZ Nisko — Główny Punkt Zasilania`, category: 'energy',
    lat: 50.518, lng: 22.15, risk: 'critical', sector: 'E',
    description: `Power Substation · tier 1 · Nisko — stacja 110/15 kV`,
    resources: {"Podatność": "8.5/10"} },
  { id: 80, name: `Linia 110kV Stalowa Wola — Nisko`, category: 'energy',
    lat: 50.55, lng: 22.1, risk: 'critical', sector: 'B',
    description: `Power Line · tier 1 · Linia napowietrzna 110kV — odcinek SW-Nisko`,
    resources: {"Podatność": "8.0/10"} },
  { id: 81, name: `Linia 110kV Stalowa Wola — Tarnobrzeg`, category: 'energy',
    lat: 50.59, lng: 22.01, risk: 'critical', sector: 'B',
    description: `Power Line · tier 1 · Linia napowietrzna 110kV — kierunek Tarnobrzeg`,
    resources: {"Podatność": "8.0/10"} },
  { id: 82, name: `Ujęcie wody 'Krzyżowe Drogi'`, category: 'water',
    lat: 50.565, lng: 22.065, risk: 'critical', sector: 'B',
    description: `Water Intake · tier 1 · Stalowa Wola, rejon Krzyżowych Dróg`,
    resources: {"Podatność": "8.0/10"} },
  { id: 83, name: `Ujęcie wody 'Stare Ujęcie'`, category: 'water',
    lat: 50.575, lng: 22.07, risk: 'critical', sector: 'B',
    description: `Water Intake · tier 1 · Stalowa Wola — Stare Ujęcie`,
    resources: {"Podatność": "8.0/10"} },
  { id: 84, name: `Miejska Oczyszczalnia Ścieków (MOS)`, category: 'water',
    lat: 50.555, lng: 22.07, risk: 'high', sector: 'B',
    description: `Wastewater Treatment · tier 1 · ul. Działkowa 1, Stalowa Wola`,
    resources: {"Podatność": "7.5/10"} },
  { id: 85, name: `Stacja redukcyjno-pomiarowa gazu — Stalowa Wola`, category: 'energy',
    lat: 50.57, lng: 22.06, risk: 'critical', sector: 'B',
    description: `Gas Station Reduction · tier 1 · Stalowa Wola — strefa przemysłowa`,
    resources: {"Podatność": "8.5/10"} },
  { id: 86, name: `Sieć ciepłownicza PGE Energia Ciepła — magistrala`, category: 'energy',
    lat: 50.575, lng: 22.05, risk: 'high', sector: 'B',
    description: `Heating Network · tier 2 · Magistrala ciepłownicza Stalowa Wola`,
    resources: {"Podatność": "6.5/10"} },
  { id: 87, name: `Zbiornik retencyjny wody pitnej — Stalowa Wola`, category: 'water',
    lat: 50.58, lng: 22.07, risk: 'medium', sector: 'B',
    description: `Water Reservoir · tier 2 · Stalowa Wola — zbiornik wyrównawczy MZK`,
    resources: {"Podatność": "6.0/10"} },
  { id: 88, name: `Magazyn paliw rezerwy strategicznej (RARS)`, category: 'chemical',
    lat: 50.55, lng: 22.05, risk: 'critical', sector: 'B',
    description: `Fuel Depot · tier 1 · Stalowa Wola — strefa przemysłowa (założenie metodologiczne)`,
    resources: {"Podatność": "9.0/10"} },
  { id: 89, name: `Komenda Powiatowa Policji w Stalowej Woli`, category: 'rescue',
    lat: 50.5795, lng: 22.0568, risk: 'high', sector: 'B',
    description: `Police Hq · tier 1 · ul. Popiełuszki 24, 37-450 Stalowa Wola`,
    resources: {"Podatność": "7.0/10"} },
  { id: 90, name: `Komenda Powiatowa Policji w Nisku`, category: 'rescue',
    lat: 50.52, lng: 22.1465, risk: 'high', sector: 'E',
    description: `Police Hq · tier 1 · ul. Sandomierska 6, 37-400 Nisko`,
    resources: {"Podatność": "6.5/10"} },
  { id: 91, name: `Komisariat Policji w Pysznicy`, category: 'rescue',
    lat: 50.545, lng: 22.085, risk: 'medium', sector: 'N',
    description: `Police Station · tier 2 · Pysznica`,
    resources: {"Podatność": "5.0/10"} },
  { id: 92, name: `Komisariat Policji w Zaklikowie`, category: 'rescue',
    lat: 50.76, lng: 22.13, risk: 'medium', sector: 'NW',
    description: `Police Station · tier 2 · Zaklików`,
    resources: {"Podatność": "4.5/10"} },
  { id: 93, name: `JRG Państwowej Straży Pożarnej — Nisko`, category: 'rescue',
    lat: 50.518, lng: 22.143, risk: 'high', sector: 'E',
    description: `Fire Station · tier 1 · Nisko`,
    resources: {"Podatność": "6.0/10"} },
  { id: 94, name: `32 Batalion Lekkiej Piechoty (WOT) — Nisko`, category: 'industrial',
    lat: 50.515, lng: 22.15, risk: 'high', sector: 'E',
    description: `Military Unit · tier 1 · Nisko — koszary (lokalizacja zbiorcza)`,
    resources: {"Podatność": "7.5/10"} },
  { id: 95, name: `Wojskowe Centrum Rekrutacji — Nisko (b. WKU)`, category: 'administration',
    lat: 50.519, lng: 22.147, risk: 'medium', sector: 'E',
    description: `Military Recruitment · tier 2 · Nisko`,
    resources: {"Podatność": "5.5/10"} },
  { id: 96, name: `Urząd Miasta Stalowa Wola`, category: 'administration',
    lat: 50.581, lng: 22.051, risk: 'high', sector: 'B',
    description: `City Hall · tier 1 · ul. Wolności 7, 37-450 Stalowa Wola`,
    resources: {"Podatność": "7.0/10"} },
  { id: 97, name: `Starostwo Powiatowe w Stalowej Woli`, category: 'administration',
    lat: 50.579, lng: 22.053, risk: 'high', sector: 'B',
    description: `County Hall · tier 1 · ul. Podleśna 15, 37-450 Stalowa Wola`,
    resources: {"Podatność": "6.5/10"} },
  { id: 98, name: `Urząd Miasta i Gminy Nisko`, category: 'administration',
    lat: 50.52, lng: 22.148, risk: 'high', sector: 'E',
    description: `City Hall · tier 1 · Plac Wolności 14, 37-400 Nisko`,
    resources: {"Podatność": "6.5/10"} },
  { id: 99, name: `Urząd Gminy Pysznica`, category: 'administration',
    lat: 50.545, lng: 22.086, risk: 'medium', sector: 'N',
    description: `City Hall · tier 2 · ul. Wolności 322, 37-403 Pysznica`,
    resources: {"Podatność": "5.0/10"} },
  { id: 100, name: `Urząd Gminy Zaleszany`, category: 'administration',
    lat: 50.68, lng: 21.89, risk: 'medium', sector: 'S',
    description: `City Hall · tier 2 · ul. T. Kościuszki 16, 37-415 Zaleszany`,
    resources: {"Podatność": "4.5/10"} },
  { id: 101, name: `Urząd Gminy Bojanów`, category: 'administration',
    lat: 50.545, lng: 21.98, risk: 'medium', sector: 'W',
    description: `City Hall · tier 2 · Parkowa 5, 37-433 Bojanów`,
    resources: {"Podatność": "4.5/10"} },
  { id: 102, name: `Urząd Gminy Radomyśl nad Sanem`, category: 'administration',
    lat: 50.68, lng: 22.05, risk: 'medium', sector: 'SE',
    description: `City Hall · tier 2 · Rynek 32, 37-455 Radomyśl nad Sanem`,
    resources: {"Podatność": "4.5/10"} },
  { id: 103, name: `Urząd Gminy Zaklików`, category: 'administration',
    lat: 50.76, lng: 22.13, risk: 'medium', sector: 'NW',
    description: `City Hall · tier 2 · ul. Zachodnia 15, 37-470 Zaklików`,
    resources: {"Podatność": "4.5/10"} },
  { id: 104, name: `Sąd Rejonowy w Stalowej Woli`, category: 'administration',
    lat: 50.5775, lng: 22.051, risk: 'medium', sector: 'B',
    description: `Court · tier 2 · ul. Popiełuszki 7, 37-450 Stalowa Wola`,
    resources: {"Podatność": "5.0/10"} },
  { id: 105, name: `Prokuratura Rejonowa Stalowa Wola`, category: 'administration',
    lat: 50.578, lng: 22.0515, risk: 'medium', sector: 'B',
    description: `Prosecutor · tier 2 · ul. Popiełuszki, Stalowa Wola`,
    resources: {"Podatność": "4.5/10"} },
  { id: 106, name: `Urząd Skarbowy w Stalowej Woli`, category: 'administration',
    lat: 50.575, lng: 22.049, risk: 'low', sector: 'B',
    description: `Tax Office · tier 3 · ul. Hutnicza 15, Stalowa Wola`,
    resources: {"Podatność": "3.5/10"} },
  { id: 107, name: `LiuGong Dressta Machinery — Stalowa Wola`, category: 'industrial',
    lat: 50.578, lng: 22.04, risk: 'medium', sector: 'B',
    description: `Industry · tier 2 · ul. Kwiatkowskiego, Stalowa Wola — dawny teren HSW`,
    resources: {"Podatność": "6.0/10"} },
  { id: 108, name: `Magazyn paliw EC Stalowa Wola (węgiel/biomasa)`, category: 'chemical',
    lat: 50.586, lng: 22.026, risk: 'high', sector: 'B',
    description: `Fuel Storage Plant · tier 1 · ul. Energetyków 13, 37-450 Stalowa Wola`,
    resources: {"Podatność": "7.5/10"} },
  { id: 109, name: `Rejon Energetyczny PGE Dystrybucja — SW`, category: 'administration',
    lat: 50.58, lng: 22.05, risk: 'medium', sector: 'B',
    description: `Utility Office · tier 2 · Stalowa Wola — biuro RE`,
    resources: {"Podatność": "5.5/10"} },
  { id: 110, name: `Dyspozytornia MZK Stalowa Wola`, category: 'administration',
    lat: 50.575, lng: 22.05, risk: 'medium', sector: 'B',
    description: `Utility Office · tier 2 · MZK Sp. z o.o., Stalowa Wola`,
    resources: {"Podatność": "5.5/10"} },
  { id: 111, name: `Piekarnia przemysłowa — Stalowa Wola`, category: 'food',
    lat: 50.57, lng: 22.05, risk: 'medium', sector: 'B',
    description: `Food Production · tier 2 · Stalowa Wola`,
    resources: {"Podatność": "4.0/10"} },
  { id: 112, name: `Hipermarket strategiczny — SW (Galeria)`, category: 'food',
    lat: 50.579, lng: 22.058, risk: 'low', sector: 'B',
    description: `Retail Strategic · tier 3 · ul. Wolności, Stalowa Wola — Galeria`,
    resources: {"Podatność": "3.5/10"} },
  { id: 113, name: `Radio Leliwa — nadajnik lokalny`, category: 'telecom',
    lat: 50.578, lng: 22.05, risk: 'medium', sector: 'B',
    description: `Broadcast Radio · tier 2 · Stalowa Wola — studio`,
    resources: {"Podatność": "5.0/10"} },
  { id: 114, name: `Lokalne centrum danych / serwerownia urzędu`, category: 'telecom',
    lat: 50.581, lng: 22.051, risk: 'medium', sector: 'B',
    description: `Data Center · tier 2 · UM Stalowa Wola — serwerownia`,
    resources: {"Podatność": "6.0/10"} },
  { id: 115, name: `Cmentarz komunalny — Stalowa Wola`, category: 'administration',
    lat: 50.565, lng: 22.07, risk: 'low', sector: 'B',
    description: `Cemetery · tier 3 · ul. Cmentarna, Stalowa Wola`,
    resources: {"Podatność": "2.0/10"} },
]

export const GRAPH_EDGES = [
  { source: 2, target: 1, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 1, type: 'water', weight: 1.0, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 85, target: 1, type: 'fuel', weight: 1.0, hoursToImpact: 0.17, note: `HSW potrzebuje gazu do procesów technologicznych (piece, obróbka cieplna).` },
  { source: 75, target: 1, type: 'transport', weight: 1.0, hoursToImpact: 0.0, note: `Dostawy materiałów i odbiór produktów.` },
  { source: 68, target: 1, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Kolejowy transport ciężki.` },
  { source: 4, target: 2, type: 'energy', weight: 0.5, hoursToImpact: 0.03, note: `EC jest lokalnym źródłem mocy. Przy braku EC sieć 110kV przejmuje obciążenie.` },
  { source: 81, target: 2, type: 'energy', weight: 0.5, hoursToImpact: 0.02, note: `Linia 110kV od strony Tarnobrzega — jedno z zasilań.` },
  { source: 4, target: 3, type: 'energy', weight: 0.5, hoursToImpact: 0.03, note: `EC jest lokalnym źródłem mocy. Przy braku EC sieć 110kV przejmuje obciążenie.` },
  { source: 2, target: 4, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 85, target: 4, type: 'fuel', weight: 1.0, hoursToImpact: 0.0, note: `EC Stalowa Wola jest gazowo-parowa (PGE EC) — bez gazu nie działa.` },
  { source: 108, target: 4, type: 'fuel', weight: 0.5, hoursToImpact: 0.5, note: `Magazyn paliw EC — bufor lokalny.` },
  { source: 5, target: 4, type: 'water', weight: 0.5, hoursToImpact: 1.0, note: `Woda technologiczna do chłodzenia.` },
  { source: 2, target: 5, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 82, target: 5, type: 'water', weight: 1.0, hoursToImpact: 1.0, note: `Jedno z dwóch ujęć MZK. Drugie jako backup.` },
  { source: 83, target: 5, type: 'water', weight: 1.0, hoursToImpact: 1.0, note: `Drugie ujęcie MZK.` },
  { source: 2, target: 6, type: 'energy', weight: 1.0, hoursToImpact: 24.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 1440 min, potem stop.` },
  { source: 5, target: 6, type: 'water', weight: 1.0, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 6, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 6, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 12, target: 6, type: 'energy', weight: 0.5, hoursToImpact: 0.0, note: `Szpital Nisko jako redundancja (~45 min jazdy).` },
  { source: 2, target: 8, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 10, target: 8, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 77, target: 8, type: 'fuel', weight: 0.5, hoursToImpact: 24.0, note: `Tankowanie pojazdów. Bufor lokalny ~24h.` },
  { source: 11, target: 8, type: 'telecom', weight: 0.5, hoursToImpact: 0.17, note: `CZK koordynuje akcje ratownicze powiatu.` },
  { source: 2, target: 9, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 10, target: 9, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 77, target: 9, type: 'fuel', weight: 0.5, hoursToImpact: 24.0, note: `Tankowanie pojazdów. Bufor lokalny ~24h.` },
  { source: 11, target: 9, type: 'telecom', weight: 0.5, hoursToImpact: 0.17, note: `CZK koordynuje akcje ratownicze powiatu.` },
  { source: 2, target: 10, type: 'energy', weight: 1.0, hoursToImpact: 3.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 180 min, potem stop.` },
  { source: 2, target: 11, type: 'energy', weight: 1.0, hoursToImpact: 12.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 720 min, potem stop.` },
  { source: 5, target: 11, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 11, type: 'telecom', weight: 0.5, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 79, target: 12, type: 'energy', weight: 1.0, hoursToImpact: 24.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 1440 min, potem stop.` },
  { source: 5, target: 12, type: 'water', weight: 1.0, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 12, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 12, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 6, target: 12, type: 'energy', weight: 0.5, hoursToImpact: 0.0, note: `Szpital PCK jako redundancja.` },
  { source: 2, target: 13, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 13, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 13, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 77, target: 13, type: 'fuel', weight: 0.5, hoursToImpact: 24.0, note: `Tankowanie pojazdów. Bufor lokalny ~24h.` },
  { source: 11, target: 13, type: 'telecom', weight: 0.5, hoursToImpact: 0.17, note: `CZK koordynuje akcje ratownicze powiatu.` },
  { source: 79, target: 14, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 14, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 14, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 77, target: 14, type: 'fuel', weight: 0.5, hoursToImpact: 24.0, note: `Tankowanie pojazdów. Bufor lokalny ~24h.` },
  { source: 11, target: 14, type: 'telecom', weight: 0.5, hoursToImpact: 0.17, note: `CZK koordynuje akcje ratownicze powiatu.` },
  { source: 2, target: 15, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 15, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 16, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 16, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 17, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 17, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 79, target: 18, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 18, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 19, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 10, target: 19, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 2, target: 20, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 2, target: 21, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 21, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 22, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 22, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 22, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 23, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 23, type: 'water', weight: 1.0, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 23, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 24, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 24, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 25, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 25, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 26, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 26, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 27, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 27, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 28, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 28, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 29, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 29, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 30, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 30, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 31, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 31, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 32, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 32, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 33, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 33, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 34, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 34, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 35, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 35, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 36, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 36, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 37, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 37, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 38, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 38, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 39, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 39, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 40, type: 'energy', weight: 1.0, hoursToImpact: 12.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 720 min, potem stop.` },
  { source: 5, target: 40, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 41, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 41, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 42, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 42, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 43, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 43, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 44, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 44, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 45, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 5, target: 45, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 1, target: 45, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Schrony zakładowe — zasilane z sieci wewnętrznej HSW.` },
  { source: 2, target: 46, type: 'energy', weight: 1.0, hoursToImpact: 6.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 360 min, potem stop.` },
  { source: 5, target: 46, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 3, target: 46, type: 'energy', weight: 1.0, hoursToImpact: 6.0, note: `Nowoczesny schron — własny UPS/generator.` },
  { source: 2, target: 47, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 47, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 47, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 48, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 48, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 48, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 49, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 49, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 49, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 50, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 50, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 50, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 51, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 51, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 51, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 52, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 52, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 52, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 53, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 53, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 53, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 54, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 54, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 54, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 55, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 55, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 55, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 56, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 56, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 56, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 57, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 57, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 57, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 58, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 58, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 58, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 79, target: 59, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 59, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 59, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 60, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 60, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 60, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 7, target: 60, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.` },
  { source: 2, target: 61, type: 'energy', weight: 1.0, hoursToImpact: 1.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 60 min, potem stop.` },
  { source: 5, target: 61, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 62, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 62, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 86, target: 62, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 7, target: 64, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.` },
  { source: 2, target: 68, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 73, target: 68, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Stacja bez linii kolejowej traci funkcję.` },
  { source: 2, target: 69, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 73, target: 69, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Stacja bez linii kolejowej traci funkcję.` },
  { source: 2, target: 70, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 73, target: 70, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Stacja bez linii kolejowej traci funkcję.` },
  { source: 79, target: 71, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 0 min, potem stop.` },
  { source: 73, target: 71, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Stacja bez linii kolejowej traci funkcję.` },
  { source: 2, target: 72, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 65, target: 73, type: 'transport', weight: 1.0, hoursToImpact: 0.0, note: `Przeprawa przez San — bez mostu linia 68 przerwana.` },
  { source: 2, target: 77, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 7, target: 78, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.` },
  { source: 4, target: 79, type: 'energy', weight: 0.5, hoursToImpact: 0.03, note: `EC jest lokalnym źródłem mocy. Przy braku EC sieć 110kV przejmuje obciążenie.` },
  { source: 80, target: 79, type: 'energy', weight: 1.0, hoursToImpact: 0.02, note: `Główne zasilanie GPZ Nisko z linii SW–Nisko.` },
  { source: 7, target: 80, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.` },
  { source: 2, target: 82, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 2, target: 83, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 2, target: 84, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 84, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 85, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 2, target: 86, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 4, target: 86, type: 'energy', weight: 1.0, hoursToImpact: 0.17, note: `Magistrala bierze ciepło z EC.` },
  { source: 2, target: 87, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 2, target: 88, type: 'energy', weight: 1.0, hoursToImpact: 1.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 60 min, potem stop.` },
  { source: 2, target: 89, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 10, target: 89, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 79, target: 90, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 240 min, potem stop.` },
  { source: 10, target: 90, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 2, target: 91, type: 'energy', weight: 1.0, hoursToImpact: 1.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 60 min, potem stop.` },
  { source: 10, target: 91, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 7, target: 91, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.` },
  { source: 89, target: 91, type: 'telecom', weight: 0.5, hoursToImpact: 0.17, note: `Komenda powiatowa koordynuje dyżury.` },
  { source: 2, target: 92, type: 'energy', weight: 1.0, hoursToImpact: 1.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 60 min, potem stop.` },
  { source: 10, target: 92, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 67, target: 92, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.` },
  { source: 89, target: 92, type: 'telecom', weight: 0.5, hoursToImpact: 0.17, note: `Komenda powiatowa koordynuje dyżury.` },
  { source: 79, target: 93, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 240 min, potem stop.` },
  { source: 10, target: 93, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 77, target: 93, type: 'fuel', weight: 0.5, hoursToImpact: 24.0, note: `Tankowanie pojazdów. Bufor lokalny ~24h.` },
  { source: 11, target: 93, type: 'telecom', weight: 0.5, hoursToImpact: 0.17, note: `CZK koordynuje akcje ratownicze powiatu.` },
  { source: 79, target: 94, type: 'energy', weight: 1.0, hoursToImpact: 8.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 480 min, potem stop.` },
  { source: 10, target: 94, type: 'telecom', weight: 0.5, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 77, target: 94, type: 'fuel', weight: 0.5, hoursToImpact: 24.0, note: `Tankowanie pojazdów. Bufor lokalny ~24h.` },
  { source: 79, target: 95, type: 'energy', weight: 1.0, hoursToImpact: 1.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 60 min, potem stop.` },
  { source: 2, target: 96, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 96, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 96, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 96, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 97, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 97, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 97, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 97, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 79, target: 98, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_nisko. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 98, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 98, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 98, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 99, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 99, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 99, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 99, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 7, target: 99, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.` },
  { source: 2, target: 100, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 100, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 100, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 100, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 101, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 101, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 101, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 101, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 102, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 102, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 102, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 102, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 2, target: 103, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 103, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 103, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 86, target: 103, type: 'energy', weight: 0.5, hoursToImpact: 4.0, note: `Sezon grzewczy X-IV. Przy braku ciepła — degradacja warunków, nie wyłączenie.` },
  { source: 67, target: 103, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Fizyczne odcięcie od głównej części SW. Most lokalny jako objazd.` },
  { source: 2, target: 104, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 104, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 104, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 2, target: 105, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 105, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 10, target: 105, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 2, target: 106, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 2, target: 107, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 107, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 85, target: 107, type: 'fuel', weight: 0.5, hoursToImpact: 0.25, note: `` },
  { source: 2, target: 108, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 68, target: 108, type: 'transport', weight: 0.5, hoursToImpact: 0.0, note: `Dostawy węgla/biomasy koleją.` },
  { source: 2, target: 109, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 10, target: 109, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 2, target: 110, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 10, target: 110, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 2, target: 111, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 111, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 85, target: 111, type: 'fuel', weight: 1.0, hoursToImpact: 0.17, note: `Piekarnia — gaz do pieców.` },
  { source: 2, target: 112, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 112, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
  { source: 2, target: 113, type: 'energy', weight: 1.0, hoursToImpact: 4.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 240 min, potem stop.` },
  { source: 10, target: 113, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 2, target: 114, type: 'energy', weight: 1.0, hoursToImpact: 2.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 120 min, potem stop.` },
  { source: 10, target: 114, type: 'telecom', weight: 1.0, hoursToImpact: 1.0, note: `Łączność komórkowa LTE/5G. Służby mają radia rezerwowe.` },
  { source: 2, target: 115, type: 'energy', weight: 1.0, hoursToImpact: 0.0, note: `Zasilanie z gpz_sw_1. Przy awarii: bufor 0 min, potem stop.` },
  { source: 5, target: 115, type: 'water', weight: 0.5, hoursToImpact: 2.0, note: `Woda pitna z SUW. Mały bufor (zbiorniki lokalne).` },
]

export const SENSORS = [
  { id: 1, lat: 50.5833, lng: 22.0500, radius: 1500, type: 'IMINT + Audio', label: 'Sensor A — Centrum' },
  { id: 2, lat: 50.582,  lng: 22.049,  radius: 1000, type: 'IMINT',         label: 'Sensor B — HSW' },
  { id: 3, lat: 50.5731, lng: 22.0555, radius: 900,  type: 'Audio',         label: 'Sensor C — Szpital' },
  { id: 4, lat: 50.5640, lng: 22.0420, radius: 1200, type: 'Radar',         label: 'Radar D — Most San' },
]

export const CUAV_ASSETS = [
  { id: 1, lat: 50.5831, lng: 22.0510, label: 'C-UAS Alfa-3',  range: 3000, available: true  },
  { id: 2, lat: 50.5720, lng: 22.0350, label: 'C-UAS Beta-1',  range: 2500, available: false },
  { id: 3, lat: 50.5950, lng: 22.0600, label: 'C-UAS Gamma-2', range: 2000, available: false },
]