// ============================================================
// STEEL SENTINEL — Local data (fallback when API unavailable)
// ============================================================

export const STALOWA_WOLA_CENTER = [50.5833, 22.0500]

export const CATEGORIES = {
  energy:         { label: 'Energetyczna',     icon: '⚡', color: '#ffeb3b' },
  water:          { label: 'Wodociągowa',       icon: '💧', color: '#4fc3f7' },
  health:         { label: 'Ochrona zdrowia',   icon: '🏥', color: '#f48fb1' },
  transport:      { label: 'Transportowa',      icon: '🌉', color: '#a5d6a7' },
  telecom:        { label: 'Łączność',          icon: '📡', color: '#ce93d8' },
  industrial:     { label: 'Przemysłowa',       icon: '🏭', color: '#ef9a9a' },
  administration: { label: 'Administracja',     icon: '🏛️', color: '#90caf9' },
  rescue:         { label: 'Ratownicza',        icon: '🚒', color: '#ffcc80' },
  chemical:       { label: 'Chemiczna/Paliwa',  icon: '🛢️', color: '#ff8a65' },
  food:           { label: 'Zaopatrzenie',      icon: '🏪', color: '#c5e1a5' },
}

export const INFRASTRUCTURE = [
  {
    id: 1,
    name: 'HSW S.A. — Huta Stalowa Wola',
    category: 'industrial',
    lat: 50.5731, lng: 22.0442,
    risk: 'critical',
    sector: 'A',
    description: 'Główny zakład produkcji sprzętu obronnego. Produkuje m.in. armatohaubice Krab, BWP Borsuk.',
    resources: { 'Zatrudnienie': '3 200 os.', 'Produkcja': 'Operacyjna', 'Ochrona': 'Wojskowa' },
  },
  {
    id: 2,
    name: 'Szpital Powiatowy im. PCK',
    category: 'health',
    lat: 50.5821, lng: 22.0531,
    risk: 'critical',
    sector: 'B',
    description: 'Jedyny szpital w mieście. Izba przyjęć, SOR, blok operacyjny.',
    resources: { 'Łóżka': '312', 'Rezerwy O2': '18h', 'Rezerwy wody': '24h', 'Generator': 'Tak (72h)' },
  },
  {
    id: 3,
    name: 'GPZ Stalowa Wola — Stacja 110kV',
    category: 'energy',
    lat: 50.5780, lng: 22.0380,
    risk: 'critical',
    sector: 'A',
    description: 'Główny punkt zasilania miasta. Transformator 110/15kV. Zasilanie 85% odbiorców.',
    resources: { 'Obciążenie': '68%', 'Rezerwa': '32%', 'UPS': '4h' },
  },
  {
    id: 4,
    name: 'Przepompownia Wody — Centrum',
    category: 'water',
    lat: 50.5900, lng: 22.0610,
    risk: 'high',
    sector: 'C',
    description: 'Główna przepompownia dystrybucji wody. Zasila 70% miejskiej sieci.',
    resources: { 'Wydajność': '4 200 m³/d', 'Ciśnienie': 'Nominalne', 'Rezerwa': '0h bez prądu' },
  },
  {
    id: 5,
    name: 'Stacja Uzdatniania Wody — SUW',
    category: 'water',
    lat: 50.5945, lng: 22.0680,
    risk: 'high',
    sector: 'C',
    description: 'Ujęcie i uzdatnianie wody z rzeki San. Zbiorniki buforowe 2×5 000 m³.',
    resources: { 'Produkcja': '8 000 m³/d', 'Rezerwa zbiornikowa': '30h', 'Chlorowanie': 'Aktywne' },
  },
  {
    id: 6,
    name: 'Urząd Miasta Stalowa Wola',
    category: 'administration',
    lat: 50.5841, lng: 22.0511,
    risk: 'medium',
    sector: 'B',
    description: 'Siedziba władz miejskich. Centrum koordynacji zarządzania kryzysowego.',
    resources: { 'Status': 'Aktywny', 'Łączność': 'Radiowa+IP' },
  },
  {
    id: 7,
    name: 'Centrum Zarządzania Kryzysowego',
    category: 'administration',
    lat: 50.5848, lng: 22.0522,
    risk: 'critical',
    sector: 'B',
    description: 'CZK — centrum operacyjne na czas kryzysu. Łączność ze służbami.',
    resources: { 'Status': 'Gotowość', 'Systemy łączności': '4 kanały', 'UPS': '8h' },
  },
  {
    id: 8,
    name: 'Komenda Miejska PSP',
    category: 'rescue',
    lat: 50.5862, lng: 22.0487,
    risk: 'high',
    sector: 'B',
    description: 'Jednostka ratowniczo-gaśnicza. 4 wozy bojowe, CBRN.',
    resources: { 'Jednostki': '4/4', 'Stan wody': '24 000L', 'CBRN': 'Wyposażona' },
  },
  {
    id: 9,
    name: 'Komenda Miejska Policji',
    category: 'rescue',
    lat: 50.5845, lng: 22.0530,
    risk: 'medium',
    sector: 'B',
    description: 'KMP Stalowa Wola. Nadzór porządku i koordynacja ewakuacji.',
    resources: { 'Patrole aktywne': '6', 'Łączność': 'Radio TETRA' },
  },
  {
    id: 10,
    name: 'Mast Telekomunikacyjny — ul. Energetyków',
    category: 'telecom',
    lat: 50.5810, lng: 22.0555,
    risk: 'high',
    sector: 'B',
    description: 'Główny mast retransmisyjny. Operatorzy: Play, Orange, T-Mobile, Plus.',
    resources: { 'Zasięg': '15 km', 'UPS': '6h', 'Łącza radiowe': '8' },
  },
  {
    id: 11,
    name: 'Most drogowy DK77 — rzeka San',
    category: 'transport',
    lat: 50.5640, lng: 22.0420,
    risk: 'high',
    sector: 'D',
    description: 'Jedyna przeprawa mostowa przez San na osi N-S. Nośność 60t.',
    resources: { 'Nośność': '60t', 'Długość': '380m', 'Alternatywa': 'Brak (18km)' },
  },
  {
    id: 12,
    name: 'PKP Stalowa Wola Centrum',
    category: 'transport',
    lat: 50.5830, lng: 22.0400,
    risk: 'medium',
    sector: 'A',
    description: 'Węzeł kolejowy. Linia 68. Znaczenie logistyczne dla dostaw.',
    resources: { 'Linie': '1 (68)', 'Ładowność': '80 wag./d', 'Status': 'Aktywny' },
  },
  {
    id: 13,
    name: 'Zbiornik Paliw — HSW Logistyka',
    category: 'chemical',
    lat: 50.5710, lng: 22.0390,
    risk: 'high',
    sector: 'A',
    description: 'Zbiorniki ON i benzyny dla zakładu HSW. Pojemność 500 m³.',
    resources: { 'Pojemność': '500 m³', 'Stan': '67%', 'Klasa zagrożenia': 'I' },
  },
  {
    id: 14,
    name: 'Rozdzielnia Gazu — GAZ-SYSTEM',
    category: 'energy',
    lat: 50.5760, lng: 22.0430,
    risk: 'high',
    sector: 'A',
    description: 'Stacja redukcyjno-pomiarowa gazu. Zasila miasto i przemysł.',
    resources: { 'Przepływ': '12 000 Nm³/h', 'Ciśnienie': '5,5 MPa', 'Odcięcie': 'Zdalne' },
  },
  {
    id: 15,
    name: 'Oczyszczalnia Ścieków — Magistrala',
    category: 'water',
    lat: 50.5650, lng: 22.0580,
    risk: 'medium',
    sector: 'D',
    description: 'Mechaniczno-biologiczna oczyszczalnia. Zrzut do rzeki San.',
    resources: { 'Przepustowość': '18 000 m³/d', 'Status': 'Operacyjna' },
  },
  {
    id: 16,
    name: 'Centrum Danych — Urząd Miasta',
    category: 'telecom',
    lat: 50.5838, lng: 22.0508,
    risk: 'high',
    sector: 'B',
    description: 'Serwerownia miejska. Systemy CCTV, rejestry, platforma kryzysowa.',
    resources: { 'UPS': '4h', 'Klimatyzacja': 'Redundantna', 'Backup': 'Chmura' },
  },
]

export const GRAPH_EDGES = [
  // GPZ zasila wszystko elektrycznością
  { source: 3, target: 1,  type: 'energy',    weight: 1.0, hoursToImpact: 0 },
  { source: 3, target: 2,  type: 'energy',    weight: 1.0, hoursToImpact: 4, note: 'Generator 72h' },
  { source: 3, target: 4,  type: 'energy',    weight: 1.0, hoursToImpact: 0, note: 'Pompy bez zasilania stają natychmiast' },
  { source: 3, target: 5,  type: 'energy',    weight: 1.0, hoursToImpact: 0 },
  { source: 3, target: 7,  type: 'energy',    weight: 1.0, hoursToImpact: 8, note: 'UPS 8h' },
  { source: 3, target: 8,  type: 'energy',    weight: 0.5, hoursToImpact: 0 },
  { source: 3, target: 10, type: 'energy',    weight: 1.0, hoursToImpact: 6, note: 'UPS 6h' },
  { source: 3, target: 16, type: 'energy',    weight: 1.0, hoursToImpact: 4 },
  { source: 14, target: 3, type: 'fuel',      weight: 0.8, hoursToImpact: 0, note: 'Gaz do agregatów' },
  // Woda
  { source: 5,  target: 4,  type: 'water',    weight: 1.0, hoursToImpact: 30, note: 'Zbiorniki buforowe 30h' },
  { source: 4,  target: 2,  type: 'water',    weight: 1.0, hoursToImpact: 24, note: 'Rezerwa szpitalna 24h' },
  { source: 4,  target: 8,  type: 'water',    weight: 1.0, hoursToImpact: 2,  note: 'Ciśnienie hydrantów' },
  { source: 4,  target: 1,  type: 'water',    weight: 0.7, hoursToImpact: 4 },
  // Łączność
  { source: 10, target: 7,  type: 'telecom',  weight: 1.0, hoursToImpact: 0 },
  { source: 7,  target: 9,  type: 'telecom',  weight: 1.0, hoursToImpact: 0 },
  { source: 7,  target: 8,  type: 'telecom',  weight: 0.8, hoursToImpact: 0 },
  { source: 16, target: 6,  type: 'telecom',  weight: 1.0, hoursToImpact: 0 },
  { source: 16, target: 7,  type: 'telecom',  weight: 1.0, hoursToImpact: 0 },
  // Transport
  { source: 11, target: 2,  type: 'transport', weight: 0.8, hoursToImpact: 0, note: 'Dostawy leków i personel' },
  { source: 11, target: 1,  type: 'transport', weight: 0.6, hoursToImpact: 0 },
  { source: 12, target: 1,  type: 'transport', weight: 0.5, hoursToImpact: 0 },
  // Paliwo
  { source: 13, target: 1,  type: 'fuel',     weight: 1.0, hoursToImpact: 0 },
  { source: 13, target: 8,  type: 'fuel',     weight: 0.6, hoursToImpact: 48 },
]

export const SENSORS = [
  { id: 1, lat: 50.5833, lng: 22.0500, radius: 1500, type: 'IMINT + Audio', label: 'Sensor A — Centrum' },
  { id: 2, lat: 50.5731, lng: 22.0442, radius: 1000, type: 'IMINT',         label: 'Sensor B — HSW' },
  { id: 3, lat: 50.5900, lng: 22.0610, radius: 900,  type: 'Audio',         label: 'Sensor C — Przepompownia' },
  { id: 4, lat: 50.5640, lng: 22.0420, radius: 1200, type: 'Radar',         label: 'Radar D — Most San' },
]

export const CUAV_ASSETS = [
  { id: 1, lat: 50.5831, lng: 22.0510, label: 'C-UAS Alfa-3', range: 3000, available: true },
  { id: 2, lat: 50.5720, lng: 22.0350, label: 'C-UAS Beta-1', range: 2500, available: false },
  { id: 3, lat: 50.5950, lng: 22.0600, label: 'C-UAS Gamma-2', range: 2000, available: false },
]
